### ISSUE TITLE
Could not decode report: Data too long (React Native iOS)

### ISSUE THREAD

**Issue by RobinTD** [getsentry/sentry-cocoa#1048]
### Environment

Sentry SaaS with React Native integration on iOS 14.4.2.

React Native 0.64 with Hermes.
RNSentry 2.4.0
Sentry 6.1.4

### Steps to Reproduce

1. Complete 100% basic vanilla integration with `Sentry.init({ dsn: ... })`.
2. Trigger crash with `Sentry.nativeCrash()`, using release build of the app.
3. Start app again so it can upload the crash report.

### Expected Result

The crash report would be sent.

### Actual Result

ERROR: SentryCrashReportFixer.c (267): char *sentrycrashcrf_fixupCrashReport(const char *): Could not decode report: Data too long

I managed to successfully send a report by increasing `SentryCrashMAX_STRINGBUFFERSIZE`. The JSON report is 234 KB, while the previous maximum was 100 KiB, which seems quite small. Most of the content is listing shared libraries, and basic crash info (nothing seems gratuitous, or specific to my setup). The two biggest sections are `debug_meta.images`, then `threads`.

Frankly it seems like a huge problem that this library is discarding valid crash reports based on arbitrary limit like that, especially when it seems so easy to hit.
If the concern is that you want to limit the size of reports, then a more reasonable strategy would be to drop some data in some instances, instead of dropping the whole crash report. However for a quick fix it seems sensible to increase the limit.

**Comment by bruno-garcia** [comment]
Historically Sentry capped crash reports to 100kb but I agree an iOS (and generally) native crashes can be larger with all the loaded symbols for example.

Lets increase this limit. Thanks for raising this!

Would you be willing to open a PR to help us out?

**Comment by marandaneto** [comment]
Server-side already supports up to 1mb per event https://develop.sentry.dev/sdk/envelopes/#size-limits

**Comment by robinclaes** [comment]
Hi, any update on this issue? We've noticed this has been happening in our React Native (iOS) app too, which is quite problematic, especially because the crash is not sent at all if the data is too long.

I've noticed that our the [sentry redux middleware](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/redux/) adds a lot of data the crashes, so removing this from our configuration is a temporary workaround.

Although ideally sentry-cocoa should be able to send larger crashes.
I don't have Swift knowledge so I sadly cannot send a PR myself.

Happy to provide more information if useful.

**Environment**
react-native: 0.64.2
@react-native/sentry: 3.4.1
sentry 7.11.0

**Error**
Could not decode report: Data too long

**Comment by marandaneto** [comment]
@robinclaes The event is sent but the server drops it, you can read up in the docs since there's a hard limit per event of 1MB.

**Comment by philipphofmann** [comment]
Instead of increasing the limit, we should apply the latest changes of [KSCrash](https://github.com/kstenerud/KSCrash/blob/master/Source/KSCrash/Recording/KSCrashReportFixer.c) for the CrashReportFixer, which doesn't have SentryCrashMAX_STRINGBUFFERSIZE anymore.
