### ISSUE TITLE
Timeout for auto-generated transactions

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1173]
`SentryTracer.waitForChildren` waits for all child spans to finish. The downside of this is that when one of these spans never finishes, the SDK never finishes the transaction. We can solve this by, for example, by starting a timeout for the transaction, which is reset every time a new span is added. When this timeout exceeds, the `SentryTracer` finishes the transaction.

**Comment by philipphofmann** [comment]
We decided not to take care of this in the first iteration of automatic performance instrumentation. There is a risk that the SDK keeps multiple references of unfinished transactions, but a timeout might not be the only solution to solve this problem. Adding a timeout brings the risk of ending transactions too early.

**Comment by philipphofmann** [comment]
Related to https://github.com/getsentry/sentry-java/issues/1811

**Comment by brustolin** [comment]
I believe we should tie a transaction with its target. If the target get out of scope we finish the transaction.
waitForChildren currently is only used for UI transactions. 
We create this transactions at ViewController 'loadView' or 'viewWillAppear'. Let's say we have a child span that never ends, we have only one transaction in memory hanging forever, this will not really cause a memory problem. 
When the ViewController disappear we can decide what to do with hanging transactions. And probably use timers here, because a ViewController can go away before a network request started with it finishes.

**Comment by marandaneto** [comment]
If this is implemented, update the spec that was written in this PR https://github.com/getsentry/develop/pull/766

**Comment by kevinrenskers** [comment]
@philipphofmann the SentryTracer class already has a bunch of idle timeout logic (`dispatchIdleTimeout`), but I am not really sure what the use of it is. It's executed by `canBeFinished` when there is a `idleTimeout` set and there are no children waiting, then waits for `idleTimeout` seconds and calls `finishInternal`.

The default value of `idleTimeout` is 0 though, so who is calling this with `idleTimeout` set to a non-zero value, and why? I don't really understand the use of it, especially since it only does something when there are no waiting children which feels like that's exactly the main point?

I can add a bunch of duplicate timeout logic next to it for the children to finish, but that feels wrong. Can we not use the existing logic, or would that break things?

**Comment by kevinrenskers** [comment]
When we start the transaction we start a timer of 30 seconds, for auto generated transactions. When the timer reaches 0 then we mark the transaction and the unfinished child spans as `deadline_exceeded` and call `finishInternal`.

When you finish the transaction, cancel the timer.

**Comment by philipphofmann** [comment]
Fixed with #2535

**Comment by marandaneto** [comment]
> Fixed with #2535

Does it require any change on the spec? See [comment](https://github.com/getsentry/sentry-cocoa/issues/1173#issuecomment-1321686225).

**Comment by philipphofmann** [comment]
Yes, it does. I have it on my list and will update it.
