### ISSUE TITLE
Add Sentry Trace HTTP Header

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1199]
The SDK should add a [sentry-trace HTTP header](https://develop.sentry.dev/sdk/performance/#header-sentry-trace) to every instrumented HTTP request with `SentryNetworkTracker` to [support distributed tracing](https://docs.sentry.io/platforms/java/performance/instrumentation/custom-instrumentation/#distributed-tracing), as specified in the [develop docs](https://develop.sentry.dev/sdk/features/#http-client-integrations). Check out the implementation in Java [as a reference](https://github.com/getsentry/sentry-java/blob/main/sentry-android-okhttp/src/main/java/io/sentry/android/okhttp/SentryOkHttpInterceptor.kt#L33-L35).

**Comment by philipphofmann** [comment]
Also, add support for [tracing origins](https://www.notion.so/sentry/68ef83ffac5b48f79b3b15a4c24a001a?v=b7f5b3d1e00348dfb7851a0f04fcab20) by adding them to the options.

**Comment by bruno-garcia** [comment]
I think this comment is relevant here: https://github.com/getsentry/sentry-java/issues/1585#issuecomment-884230182

It makes sense that the trace id doesn't need to go to all endpoints an App talks to. Currently it can be filtered with the callback the integration offers but we could look at adding the same options as the browser JS SDK.
Worth noting the browser adds that because of CORS:

> You will need to configure your web server CORS to allow the sentry-trace header. The configuration might look like "Access-Control-Allow-Headers: sentry-trace", but the configuration depends on your set up. If you do not allow the sentry-trace header, the request might be blocked.

So we have less of a need here since CORS doesn't apply here.
