### ISSUE TITLE
Provide pre-built binaries for SPM (compiling current package takes >20 seconds)

### ISSUE THREAD

**Issue by arielelkin** [getsentry/sentry-cocoa#1369]
The current Swift Package involves building the entire Sentry SDK from source, which takes 10-30 seconds:

![image](https://user-images.githubusercontent.com/1756909/136765931-b3f44da5-e56c-4645-8462-57da94b2b7a0.png)

Could we have a swift package that just provides the [the Sentry binary .frameworks](https://github.com/getsentry/sentry-cocoa/releases). Implementation is really straightforward:
https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

A broader discussion is whether Sentry's default swift package should contain _source code_ or the _pre-built framework_. I presume most people using Sentry are just integrating it as a third-party framework (rather than developing it) and faster compilation times are more important to them than having access to the source code. Have you considered providing two separate Swift packages; one for the source and one for the pre-built binary?

**Comment by philipphofmann** [comment]
@arielelkin, sorry we didn't get to this yet. If you could open a PR, it would be awesome 😃 . I think it should be an easy fix.

**Comment by arielelkin** [comment]
@philipphofmann The binary asset's url specified in Package.swift needs to point to a release asset and a tag, but that creates a chicken and egg problem. 

One solution is the following:
https://forums.swift.org/t/spm-support-basic-auth-for-non-git-binary-dependency-hosts/37878/103

> Point the Package.swift to the draft release assets
> Push the updated Package.swift + tag
> Update the draft release to use the new tag
> Move the release from draft to published

Alternatively, we could have a separate repo hosting the release assets.. Easier to implement, but has some redundancy. 

What are your thoughts?

**Comment by philipphofmann** [comment]
Sorry, @arielelkin will get back to you tomorrow.

**Comment by philipphofmann** [comment]
> Alternatively, we could have a separate repo hosting the release assets. Easier to implement, but has some redundancy.

I would like to avoid a repo for hosting, as we need to set it up, maintain, etc.

@arielelkin, we know the binary URL before creating the release. See https://github.com/getsentry/sentry-cocoa/releases/tag/8.3.1 has https://github.com/getsentry/sentry-cocoa/releases/download/8.3.1/Sentry.xcframework.zip.

Another question: can't we use the [`binarytarget(name:path:)`](https://developer.apple.com/documentation/packagedescription/target/binarytarget(name:path:))?

**Comment by arielelkin** [comment]
> we know the binary URL before creating the release. See https://github.com/getsentry/sentry-cocoa/releases/tag/8.3.1 has https://github.com/getsentry/sentry-cocoa/releases/download/8.3.1/Sentry.xcframework.zip.

Unfortunately that doesn't help; the issue is knowing the binary URL before creating the _tag_, not the release:

* `Package.swift` lives at a specific tag and must specify the binary file's URL
* We know that URL only once the file has been added to a GitHub release as an asset
* That GitHub release is only created after we push a tagged commit, in which `Package.swift` file specifies the... file's URL, which doesn't exist at that stage as the release hasn't been created yet 
* 🐔 🥚 

> Another question: can't we use the binarytarget(name:path:)?

For that to work, the .xcframework must be checked into the repo.

**Comment by philipphofmann** [comment]
We know the URL beforehand, as it follows the pattern https://github.com/getsentry/sentry-cocoa/releases/download/sdk-version/Sentry.xcframework.zip , but the problem is the checksum. It doesn't matter if we host our own repo for the `framework.zip` or if we use the artifacts of GH releases. We need to make a commit with the checksum of the `framework.zip` after GH actions created it.

Currently, our release process pulls the artifact from the commit created by crafts preReleaseCommand, such as [8.3.2](https://github.com/getsentry/sentry-cocoa/commit/3fc79ea6ebcfd726e48bea1d98f89bc3a32d5cf2). After a Sentry manager approves the release, such as [8.3.2](https://github.com/getsentry/publish/issues/2004), the publish GH action workflow would need to pull the artifact and create another commit to update the checksum of the SPM `.binaryTarget`. As far as I know, this is not possible now with our process of managing release. Craft would need a similar hook as the [`pre-release-command`](https://github.com/getsentry/craft#pre-release-command), which runs during `craft publish`. The hook would need to run before publishing the targets.

**Comment by tcwalther** [comment]
Another option is to create a second repository for this, like a mirror. I've found https://github.com/malcommac/sentry-cocoa-sdk-xcframeworks/ that does exactly that, but trusting a binary framework from an unofficial source is always a bit "meh" (plus, rn their workflow script is a bit broken and doesn't actually store the framework in the root folder - I created an issue for this, but it shows it'd be better to have an official channel).

**Comment by philipphofmann** [comment]
Thanks for the update, @tcwalther, but I prefer using the same repository. For everyone please upvote in the first comment in this issue https://github.com/getsentry/sentry-cocoa/issues/1369#issue-1022475796 to let us know how many users would love to see this being implemented.

**Comment by scogeo** [comment]
I'm chiming in for a +1 to have a separate repository to host the `Package.swift` containing `binaryTargets` and keep the current repository as a build from source(s) package.  This gives the most flexibility for building the library from source if needed and gives an option to access the officially sanctioned pre-built library at a different URL.  For example, if there was a new repo named `sentry-cocoa-xcframework`, then one could just change the URL in the package reference.

```swift
// Use for source version
.package(url: "https://github.com/getsentry/sentry-cocoa", from: "8.3.2"),
// Or, use the xcframework version
.package(url: "https://github.com/getsentry/sentry-cocoa-xcframework", from: "8.3.2"),
```

The repo that hosts the `xcframework` doesn't have to actually host or build the xcframework, it could just point at URLs back in the main `sentry-coca` repository releases.  Then just add a workflow in GitHub that updates the xcframework repo whenever a release is published in the main repo.

It would just need a `Package.swift` file similar to the following:

```swift
let package = Package(
    name: "Sentry",
    platforms: [.iOS(.v11), .macOS(.v10_13), .tvOS(.v11), .watchOS(.v4)],
    products: [
        .library(name: "Sentry", targets: ["Sentry"]),
    ],
    dependencies: [],
    targets: [
        .binaryTarget(name: "Sentry",
                      url: "https://github.com/getsentry/sentry-cocoa/releases/download/8.3.2/Sentry.xcframework.zip",
                      checksum: "e25814a875efe595b24e0a5fddd519b899aab129ab8e257673be90ae85fb4bc8")
    ]
)
```

Each release just needs to update the URL and the checksum.  Then just update the Carthage build so that the .zip file has the xcframework at the root and it will be compatible with both SPM and Carthage.

**Comment by arielelkin** [comment]
In the meantime, here's how to easily host your sentry xcframework binaries:

1. create a new folder
2. download the latest sentry xcframework from https://github.com/getsentry/sentry-cocoa/releases, unzip and place it at the root of the directory
3. create the following Package.swift file
4. commit and push
5. in your xcode project's swift package section, replace the sentry package with this
6. reduce your build time substantially

```swift
// swift-tools-version:5.5
import PackageDescription

let package = Package(
    name: "Sentry-binaries",
    platforms: [.iOS(.v11), .macOS(.v10_13), .tvOS(.v11), .watchOS(.v4)],
    products: [
        .library(
            name: "Sentry-binaries",
            targets: ["Sentry"]
        )
    ],
    targets: [
        .binaryTarget(
            name: "Sentry",
            path: "Sentry.xcframework"
        )
    ]
)
```

**Comment by lionel-alves** [comment]
Hi, any update on this? Thanks!

**Comment by philipphofmann** [comment]
@lionel-alves, no update, sorry.

**Comment by brustolin** [comment]
This will be solved in the next release
