### ISSUE TITLE
Send device locale with Events

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1438]
Discover lists `device.locale` as a search condition, see https://docs.sentry.io/product/discover-queries/query-builder/. The develop docs list the `locale` in culture context, see https://develop.sentry.dev/sdk/event-payloads/contexts/#culture-context. Figure out how to send the device locale so customers can use it in Discover. After this maybe fix the Discover or Develop docs and create an issue for the Java repo.

**Comment by marandaneto** [comment]
Android offers `device.language` with the eg `en_US` format, and `device.timezone` with the eg `Europe/Paris` format.

**Comment by philipphofmann** [comment]
Let
- [ ] Fix the description of the language of the dev docs of [device context](https://develop.sentry.dev/sdk/event-payloads/contexts/#device-context). Instead of en-US change it to en.
- [ ] As locale already exists in [Discover](https://docs.sentry.io/product/discover-queries/query-builder/#filter-by-search-conditions) and there is a [column in Snuba](https://github.com/getsentry/sentry/blob/8769f17aaf8bf76bc3cf9ac813bf65fbea48917c/src/sentry/snuba/events.py#L111-L117), we should add locale to the dev docs device context.
- [ ] https://github.com/getsentry/sentry/pull/29879/
- [ ] Send `device.locale` with the Cocoa SDK
- [ ] Add `devicel.locale` to the Android SDK
- [ ] Create a task to fix `device.language` in the next major version of Android
- [ ] Find out if we why language and locale are duplicate for device and culture context

**Comment by bruno-garcia** [comment]
> As the device.locale isn't documented in the develop docs

Turns out we added this under a new Context called `culture`. 

![image](https://user-images.githubusercontent.com/1633368/145073421-5158acb6-a6f2-482f-89cf-e4bc608090f4.png)

>  Fix the description of the language of the dev docs of device context. Instead of en-US change it to en.

This is a breaking change since these values are indexed and used to show distribution and potentially alerts. Do we need to change from one to the other? If so, what ISO format are we going from, to?

**Comment by marandaneto** [comment]
> Find out if we why language and locale are duplicate for device and culture context

`culture_context` is a new thing because of flutter, it didn't make sense to bloat the `context.device` with so much stuff, so it made sense to create a new one.
following the new format, `device.locale`, `device.language`, and `device.timezone` should be deprecated in favor of `culture_context`.
the problem is that this is a bigger change and requires bumping a major etc, I'd rather add the missing fields on iOS for now for a quick win.

**Comment by philipphofmann** [comment]
> following the new format, device.locale, device.language, and device.timezone should be deprecated in favor of culture_context.

Who said that?

I don't think `culture_context` is already indexed and you can use it in Discover.

**Comment by marandaneto** [comment]
@philipphofmann that was just the natural way going forward after adding `culture_context`, otherwise it'd give duplicated fields, see https://github.com/getsentry/develop/pull/329
its part of the unified API now for a while, but I guess only Dart and .NET have it iirc.

`culture_context` isn't indexed, yes, it should going forward.

**Comment by philipphofmann** [comment]
Why don't the develop docs then state that they are deprecated? It doesn't help to decide this in the PR and not putting this in the docs. If the official decision is they are deprecated we should communicate that on the docs. 

> culture_context isn't indexed, yes, it should going forward.

Sorry, I don't get that. Are you saying we should index it? If so, deciding in https://github.com/getsentry/develop/pull/329 to use `culture_context` and not making sure they are indexed is not nice. We have to fix that.

**Comment by marandaneto** [comment]
@philipphofmann please invite us for a call, its easier
