### ISSUE TITLE
Question: How can I attach a log file to out of memory events?

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-cocoa#1459]
_Platform:_
- [x]  iOS
- [x]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_sentry-cocoa installed with:_
- [ ] Swift Package Manager
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**7.3.0**

---

I would like to provide additional log files for my exceptions that are due to out of memory issues.

I have added a `beforeSend` hook to my `SentryOptions` but I can't figure out how I would add that attachment to the `SentryEvent` that is available to me there.

Is there a way I can conditionally add attachments based on the exception?

**Comment by philipphofmann** [comment]
Hi @eric, 

Sadly that's currently not possible. Other SDKs make that possible using [hints](https://docs.sentry.io/platforms/python/configuration/filtering/#event-hints), which we didn't add yet to the Cocoa SDK, because we had internal discussions about hints in general. 

I also can't think of a reliable workaround for this.
