### ISSUE TITLE
Use SwiftLocalHost instead of Vapor

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#1486]
Instead of using Vapor as an external server to create integration tests, we can use [SwiftLocalHost](https://github.com/depoon/SwiftLocalhost) or other similar solution that runs on the same process. This way we can assert data sent to the server.

**Comment by philipphofmann** [comment]
When trying SwiftLocalHost, I came across a few problems:

1. It doesn't support [SPM](https://github.com/depoon/SwiftLocalhost/issues/16).
2. It depends on Criollo, which has an iOS deployment target of [iOS 12](https://github.com/thecatalinstan/Criollo/blob/ef0b414abe9de39bc3ab9edaef4a9eb22cb86478/Criollo.podspec#L24). This means we also can't use Criollo tests on real devices for iOS 11 and 10.
3. Both SwiftLocalHost and Criollo are not really maintained. The [last release](https://github.com/depoon/SwiftLocalhost/releases/tag/0.0.8) of SwiftLocalHost was in February 2020, and Criollo in [July 2020](https://github.com/thecatalinstan/Criollo/releases).

Due to the problems mentioned and as we currently don't need to assert much data sent to the server, I think we should stick to Vapor instead.
