### ISSUE TITLE
API to snapshot active threads

### ISSUE THREAD

**Issue by rnystrom** [getsentry/sentry-cocoa#1490]
I see that the Sentry SDK has the ability to capture stack traces for threads internally. I'd love to be able to use this in our app as we already use Sentry (as opposed to importing another library that does the exact same thing). As far as I can tell, these mechanisms are private to the SDK right? Any suggestions on ways to access or hack-around the SDK and get the ability to capture the state of all threads at an arbitrary time?

For context, we have a an internal bug reporter and I'd like to collect the state of all threads at the time of reporting. Open to other suggestions/ideas to solve this problem!

**Comment by philipphofmann** [comment]
Hey, we have an internal class called `SentryThreadInspector`, that gets the current threads with the stacktrace only for the current thread. We don't add the stacktrace for all threads, because doing that would require pausing all threads, which we don't want to do for every captureSomething invocation. 

https://github.com/getsentry/sentry-cocoa/blob/eec5e4a78f73de42be352f3c17dbb2646fe94d55/Sources/Sentry/SentryClient.m#L431-L443

You could capture a message and then just get the stacktrace in `beforeSend` and discard the event if you want.

```swift
SentrySDK.start { options in
    options.beforeSend = { event in
        if (event.message == "Get Stacktrace") {
            event.threads. // whatever you want
            return nil
        }
        
        return event
    }
}

SentrySDK.capture(message: "Get Stacktrace")
```

That approach is definitely hacky, but it should work. We can also start a discussion to make `SentryThreadInspector.getCurrentThreads` public if you want.

**Comment by rnystrom** [comment]
Thanks @philipphofmann! I implemented your solution and it works like a charm, but missing other thread info is what I'm also interested in. I'll do some more exploring, your point about not stalling other threads makes a lot of sense.

**Comment by philipphofmann** [comment]
We add the info on other threads though. We don't add the stacktraces for all threads. We just add it for the current thread.
