### ISSUE TITLE
Add app language as event context

### ISSUE THREAD

**Issue by triplef** [getsentry/sentry-cocoa#1588]
The `device.language` context value should be populated with the active localization of the app.

This can be done as follows outside the SDK, but it would be nice to be integrated by default:

```objc
NSString *language = NSBundle.mainBundle.preferredLocalizations.firstObject;
if (language) {
	[SentrySDK configureScope:^(SentryScope *scope) {
		[scope setContextValue:@{@"language": language} forKey:@"device"];
	}];
}
```

**Comment by philipphofmann** [comment]
We recently marked `device.language` as deprecated in our dev docs. Instead, we added the [culture context](https://develop.sentry.dev/sdk/event-payloads/contexts/#culture-context), for which we already have an issue: https://github.com/getsentry/sentry-cocoa/issues/1534. The culture context will include locale instead of language. I'm going to close this now as it's a duplicate. Thanks for reporting @triplef.
