### ISSUE TITLE
App hang leads to falsely reported OOM

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1645]
### Platform

iOS

### Installed

CocoaPods

### Version

7.9.0

### Steps to Reproduce

1. Block the main thread with something like
```Swift
var i = 0
for _ in 0...1_000_000 {
    for _ in 0...1_000_000 {
        i += Int.random(in: 0...10)
        i -= 1
    }
}
```
2. Manually kill the app
3. Launch the app again

### Expected Result

No OOM, but instead an app hang, which the SDK doesn't support at the moment.

### Actual Result

The SDK falsely reports an OOM.

**Comment by philipphofmann** [comment]
We could use a [`CFRunLoopObserver` ](https://developer.apple.com/documentation/corefoundation/cfrunloopobserver-ri3) to identify if the main thread hanged to create an event for app hangs and also to avoid reporting OOMs. It is worth noting the [watchdog](https://developer.apple.com/documentation/xcode/addressing-watchdog-terminations) also terminates an app if it's not responsive for a while.

**Comment by philipphofmann** [comment]
This is related to https://github.com/getsentry/sentry-cocoa/issues/1052.

**Comment by philipphofmann** [comment]
Update the docs added with [this PR](https://github.com/getsentry/sentry-docs/pull/4645).

**Comment by philipphofmann** [comment]
Ideally, we need to add a feature for app hangs when fixing this bug. Not reporting app hangs as OOMs without an app hang feature is even worse, in my opinion. If you have a spike in app hangs now, you at least get OOMs. Otherwise, you wouldn't get any data in Sentry.

**Comment by owjsub** [comment]
Is sentry performance monitoring able to catch app hangs?

**Comment by bruno-garcia** [comment]
@owjsub These hangs reported as OOM happened when the app is killed. OOM detection happens when the app start:

"Why did the app not close gracefully in the last run"? If the SDK believes it was due to OOM, it raises the event. But sometimes the app was hanging and got killed (for example, by the user swiping up).

So it's still an issue, and not really detected by the performance product since the app was killed and the transaction that was happening was lost. One potential feature is to store ongoing transactions to disk. And in the event of a crash, (due to OOM, hang, or anything else) we can capture that transaction to get an idea of what was happening. At least know what screen was loaded, and what span was open. 

Persisting transactions might add in overhead so we need to investigate this further.

**Comment by bruno-garcia** [comment]
As suggested by @souredoutlook, please add an opt-out such as `enableAppHangTracking`
