### ISSUE TITLE
Replacing/forking KSCrash?

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-cocoa#166]
A non-zero number of my app's crashes are caused by KSCrash: 
https://github.com/kstenerud/KSCrash/issues/237
https://github.com/kstenerud/KSCrash/issues/234

Both of those issues have gone unanswered, and it seems like KS [isn't actively working](https://github.com/kstenerud/KSCrash/issues/207#issuecomment-288897920) on KSCrash at the moment (which is fine, it's open source, i get it).  That said, any chance you guys would consider forking it and rolling it into the Sentry pod?

side note: It's really weird that 3.0 no longer includes the transitive dependency on KSCrash.  What was the motivation here?  Seems like it'll make it more likely that versions won't play well together (which is another good argument for forking and rolling it into a single dependency: the Sentry pod)

**Comment by HazAT** [comment]
Hey,
The motivation behind making `KSCrash` optional was that some people wanted to use Sentry without `KSCrash`. Theoretically, someone could use his own Crashreporter and just send Events to Sentry now.

For now, we are pretty happy with `KSCrash` and we still recommend using it together with `sentry-cocoa`, that said we are currently not seeing a reason forking `KSCrash` because this means maintaining another repo.

Karl usually responds pretty fast to the PR's we send him whenever we have an issue with `KSCrash`.

If these 2 issues you mentioned currently still exists, please make a new issue here and I can look at it. Since we changed a lot in `3.0` it could be that the issues are gone.
