### ISSUE TITLE
Bump minimum supported OS versions

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#1916]
### Description

We didn't bump the minimum supported iOS, macOS, tvOS, and watchOS versions for a while. In the next major release, we should revisit if it's okay to bump them.

**Comment by brustolin** [comment]
Agreed!! Lets make it at least iOS 10

**Comment by philipphofmann** [comment]
> With iOS 16 around the corner, wouldn't it make sense to bump it to iOS 13 or so? So much less testing to do then. People still supporting very very old iOS versions can always stick with an older version of the SDK, right?

Yep, we can discuss that once 8.0.0 is approaching.

**Comment by mattjohnsonpint** [comment]
We probably need to keep supporting older devices, the question is - how old?  And what does bumping the version give us, versus no longer supporting some subset of customers?

For reference:
https://en.wikipedia.org/wiki/IOS_version_history

Reading that, it seems to be some advantage of bumping to iOS 11, since we would no longer need to build for 32-bit devices.  That would drop support for most 5th gen Apple devices (iPhone 5, etc.).

Checking our telemetry, it appears the top versions are presently:
- iOS 15.6 (60%)
- iOS 15.5 (18%)
- iOS 15.4.1 (4%)
- iOS 15.3.1 (2%)
- iOS 14.8.1 (2%)
- iOS 12.5.5 (2%)
Everything else is 1% or lower.

I believe 12.5.5 is still viable, given it's the last supported version on 6th gen devices.

On a personal note, I test using a 6th gen iPod touch, so please don't bump to 13 or I'll have to go shopping. 😄

**Comment by kevinrenskers** [comment]
> And what does bumping the version give us

The ability to use new APIs. Getting rid of a bunch of deprecated code. And when iOS 16 hits, "only" supporting 13, 14, 15 and 16 (which is still quite a lot) means much less testing across all these iOS versions as well. Plus iOS 13 and up include SwiftUI and Combine which we could support without a whole bunch of if statements everywhere. 

> or I'll have to go shopping

Buying a new Apple device sounds like fun though 😂

**Comment by philipphofmann** [comment]
Let's bump to macOS 10.13, iOS 11, tvOS 11, and watchOS 4

> Building for deployment to OS releases older than macOS 10.13, iOS 11, tvOS 11, and watchOS 4 is no longer supported. (92834476)

https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

**Comment by kevinrenskers** [comment]
Xcode recommends to increase to iOS/tvOS 12.0 instead of 11.0.

![Screenshot 2022-11-21 at 10 10 43](https://user-images.githubusercontent.com/229384/203010756-8a6cfde9-9846-404c-bb58-f7498b7d1c73.png)

Of course we can ignore this recommendation but... what was the reason to go for 11?

**Comment by philipphofmann** [comment]
> Xcode recommends to increase to iOS/tvOS 12.0 instead of 11.0.
> Of course we can ignore this recommendation but... what was the reason to go for 11?

Xcode 14 still supports 11, and we want to be backward compatible as much as possible. Between 11 and 12 there is no real difference for us. 13 would be great, but we agreed that we have to wait a bit for that.
