### ISSUE TITLE
SDK version is not displayed in dashboard

### ISSUE THREAD

**Issue by tustanivsky** [getsentry/sentry-cocoa#2010]
### Description

In sentry-unreal (Sentry plugin for Unreal Engine) we're using sentry-cocoa internally for crash capturing on iOS. After updating it to version 7.22.0 I've noticed that the SDK version is not displayed in dashboard anymore.

A similar issue was confirmed for sentry-unity as well.

![unknown](https://user-images.githubusercontent.com/3168564/181304216-a0dcc834-be73-4716-9a9e-a66b4815227e.png)
.

**Comment by brustolin** [comment]
Hello @tustanivsky, thanks for the input, we will investigate this.

**Comment by bitsandfoxes** [comment]
Unity is on `Cocoa v7.23.0` right now in the latest release and does not have this issue. Events reported through the Cocoa SDK show up as `sentry.cocoa.unity`.

**Comment by philipphofmann** [comment]
@tustanivsky, can you check the [comment above](https://github.com/getsentry/sentry-cocoa/issues/2010#issuecomment-1216467252) and let us know if you still experience the issue?

**Comment by bitsandfoxes** [comment]
I stand corrected: It's made its way into the Unity SDK as well: https://github.com/getsentry/sentry-unity/issues/950

**Comment by philipphofmann** [comment]
Ah, now I think I get it. If you pass down the SDK name `sentry.cocoa.unreal` or `sentry.cocoa.unity` the cocoa SDK doesn't send the version properly, @tustanivsky?

**Comment by tustanivsky** [comment]
> Ah, now I think I get it. If you pass down the SDK name `sentry.cocoa.unreal` or `sentry.cocoa.unity` the cocoa SDK doesn't send the version properly, @tustanivsky?

Yes, correct

**Comment by vaind** [comment]
This has been caused by #1960 - we need to adapt the Unity & Unreal SDKs to fix that.

The issue with the empty version string is caused by this line https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryOptions.m#L336

Previously if the given version was empty, it was be ignored.

https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentrySdkInfo.m#L51

Now it just writes whatever is given (nullptr)

**Comment by vaind** [comment]
I've updated the respective issues in [Unreal](https://github.com/getsentry/sentry-unreal/issues/95) & [Unity](https://github.com/getsentry/sentry-unity/issues/950) with the info that we need to use `PrivateSentrySDKOnly`.

What is missing with the current code, however, is the option to set only a name **or** a version, not both. Can someone make the changes to `PrivateSentrySDKOnly` to expose that? Ideally also a getter for both name & version because it's also [used](https://github.com/getsentry/sentry-dart/blob/e02249c3d401fb2258b22d15645a032cabae30ff/flutter/ios/Classes/SentryFlutterPluginApple.swift#L175) by the Dart SDK to add info to the events coming from Dart - reading the now deprecated `options.sdkVersion`

**Comment by philipphofmann** [comment]
Yep, we can change that easily. How important / urgent is that for you, @vaind?
