### ISSUE TITLE
Crash/Exception handling on macOS

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-cocoa#203]
https://forum.sentry.io/t/mac-app-exceptions/2274
---
I’ve created a fresh Mac app project now, connfigured Sentry in it (via CocoaPods), and added two buttons to it - one calls a missing method on an object, and the other throws an NSException using @throw (ObjC). I archived the app and exported it from Xcode.

When I run the app like this, the app doesn’t crash at all when I press the buttons. The exception is probably printed to some kind of log, but the app stays open and I get no reports.

I remembered from Crashlytics that their docs recommended setting a NSApplicationCrashOnExceptions property in the defaults to enable catching of such crashes (https://docs.fabric.io/apple/crashlytics/os-x.html). I did that here, and I am getting a report, but… it only mentions [NSApplication reportException:] and [NSApplication _crashOnException:], nothing about my code. In HockeyApp they instead have a custom NSApplication subclass that you’re supposed to configure as the “principal class”, but I couldn’t find anything like that in your docs.

Am I doing anything wrong, did I miss something? Is there anything I can do to make Sentry catch exceptions from in a Mac app?

**Comment by mackuba** [comment]
Hi,

I've played with this a bit today - I am getting exception reports pointing to the right place now. It's not perfect, because for some reason I'm getting *only* the line where it crashed, but no callers down the stack:

```objc
- (IBAction)methodMissingPressed:(id)sender {
    [self causeMethodMissingWith:sender];
}

- (void)causeMethodMissingWith:(id)sender {
    [sender lastObject];
}
```

<img width="814" alt="screen shot 2017-09-08 at 00 04 58" src="https://user-images.githubusercontent.com/28465/30188044-a80d8f98-942c-11e7-8b16-faa43af324a2.png">
<img width="810" alt="screen shot 2017-09-08 at 00 05 08" src="https://user-images.githubusercontent.com/28465/30188045-a9d2ee36-942c-11e7-9d46-5b4ed6c3e187.png">

I doubt this can be fixed easily though, because HockeyApp isn't getting the second line either, and the crash in the system dialog also only shows one line from my app.

Out of curiosity, I checked this in a debugger with a breakpoint in `reportException:`, and the exception at this point seems to include the missing line - but only when I run the app from Xcode with a debugger. If I add an NSLog there and run an archived & exported version, then the NSLog only prints one line with "SentryMacTest"... So probably nothing we can do here.


---

There's one more thing to improve: from the user's perspective, I think it's weird that the app's window disappears *and then nothing happens*. The expectation is that when an app disappears suddenly like this, a moment later the familiar system crash dialog appears, telling them that yes, the reason why it disappeared is because the whole app crashed. And then they have the option to click the "Reopen" button to automatically restart it. All of this doesn't happen if we call `exit()`...

I experimented with this a bit, since I have access to the source, and I think the best approach is to:
- set the `NSApplicationCrashOnExceptions` user default, [like in Fabric](https://docs.fabric.io/apple/crashlytics/os-x.html)
- run our handler first
- and then call `super`, which will cause a proper crash

HockeyApp does it in some other way, because they don't require setting this default and the app crashes anyway, you just need to [change the main class to `BITCrashExceptionApplication`](https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/hockeyapp-for-macos#crashreporting), but I can't check how they do it, since their SDK isn't open source.

And here's Bugsnag's version: https://docs.bugsnag.com/platforms/macos-objc/#reporting-unhandled-exceptions

**Comment by mackuba** [comment]
Hmm, I've checked the HockeyApp version again - this is what I'm getting when it crashes, but I can't figure out how they're doing it exactly:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Performing @selector(methodMissingPressed:) from sender NSButton 0x61000015c880
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8c443d42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff8c531457 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff8c3a9420 abort + 129
3   net.hockeyapp.sdk.mac         	0x0000000108a0b1f3 uncaught_exception_handler + 27
4   net.hockeyapp.sdk.mac         	0x00000001089e0ac7 -[BITCrashExceptionApplication reportException:] + 184 (BITCrashExceptionApplication.m:35)
5   net.hockeyapp.sdk.mac         	0x00000001089e0b5e -[BITCrashExceptionApplication sendEvent:] + 127 (BITCrashExceptionApplication.m:51)
6   com.apple.AppKit              	0x00007fff74654427 -[NSApplication run] + 1002
7   com.apple.AppKit              	0x00007fff7461ee0e NSApplicationMain + 1237
8   libdyld.dylib                 	0x00007fff8c315235 start + 1
```

**Comment by HazAT** [comment]
@mackuba Thanks for helping us improving our SDK 👍 
I've created a PR https://github.com/getsentry/sentry-cocoa/pull/208
which implements the behavior you described https://github.com/getsentry/sentry-cocoa/issues/203#issuecomment-327943892

Feel free to review it, I will merge it then and make a new release.

In regards to the missing frame, this will be a bit more complicated but I will check it.
I am pretty sure it's either the compiler optimizes the method away
OR
it's because KSCrash (and therefore Sentry) does not support DWARF unwinding.

**Comment by eaigner** [comment]
See https://github.com/microsoft/appcenter-sdk-apple/issues/1944 as well
