### ISSUE TITLE
TraceId not sent with error

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2048]
### Description

@thinkocapo Reported that, during his tests, trace_id was not transmitted with the error event.

![image](https://user-images.githubusercontent.com/28265868/183438157-35538bea-3fd5-45a4-8551-ac31fe7573cc.png)

Javascript equivalent [code](https://github.com/sentry-demos/application-monitoring/blob/master/react/src/components/Checkout.js#L63-L80) that do the same.

**Comment by brustolin** [comment]
@kevinrenskers Can you check this for us after your current task please? 

Thanks!!

**Comment by kevinrenskers** [comment]
Yup

**Comment by kevinrenskers** [comment]
I believe this is the exact thing we actually *want* to happen. When you look back at https://github.com/getsentry/sentry-cocoa/issues/1827, they were getting errors with the *wrong* trace ID, and that was because of user error: they were not binding the transaction to a scope. We fixes it on our end by removing the trace ID in the case of such a user error.

The real fix is for them to fix their application and to bind the transaction to the scope.

See https://github.com/getsentry/sentry-cocoa/issues/1827#issuecomment-1185549496 and https://github.com/getsentry/sentry-cocoa/pull/1975.

**Comment by kevinrenskers** [comment]
@thinkocapo does that help you? Is it clear that you need to bind the transaction of making a purchase to the scope?

**Comment by brustolin** [comment]
We figure it this out. The sample app is finishing the transaction before the HttpRequest callback is called.
