### ISSUE TITLE
Add option for start up crashes

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2283]
### Description

Add an option `enableStartupCrashDetection ` with a default of `true`, so users can disable the start up crahes detection added with #2220. 

Please also add this option to the docs.

**Comment by kevinrenskers** [comment]
Why would someone want to disable this feature?

**Comment by romtsn** [comment]
> you never want your app to be blocked at start-up.
I think this is the reason we should have it. Because we made some assumptions on the flush timeout and startup crash threshold, doesn't mean that they are correct. 2 seconds threshold might very well be enough for most of the apps in developed countries to flush out the envelopes, so that they don't even need to block and would like to disable this altogether.

Another point is - we care so much about performance and talk how we should make it a nobrainer for our customers to buy, yet introducing a feature that potentially degrades one of the core mobile vitals (app start) without a possibility to disable it. That doesn't sound right to me.

**Comment by kevinrenskers** [comment]
Then the question becomes: why would anyone want to enable it, if it causes problems? To me adding flags and options is not necessarily a good thing. The feature should either be useful and not cause problems, or should be made that way, so there is no reason to disable it. Not sure if that is possible here, but just adding a boolean seems weird to me.

**Comment by philipphofmann** [comment]
As discussed on a call with @romtsn, we decided that we don't add this option for now. We think that this feature should be on by default, and there should be no good reason to disable it, as you accept the app start being blocked if there was a crash shortly after the app start on a previous run. We can always add this option later.
