### ISSUE TITLE
Use `paths-filter` action in CI

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#2343]
### Description

The missing functionality GitHub should have for its workflow triggers: https://github.com/getsentry/paths-filter

This will cut down on a lot of wasted compute time, and headaches with flaky tests failing when it’s not even necessary to run them.

**Comment by brustolin** [comment]
Im curious to know where would this help? Do you have any scenarios in mind?

IMO, If we need a job or step to run with a specific path filter we could create a different workflow, no need to use another github action.

**Comment by brustolin** [comment]
I thought
```yaml
  pull_request:
    paths:
```
was meant for this.

**Comment by armcknight** [comment]
Sorry I didn't see your earlier message from some time ago. Check this out: https://github.com/dorny/paths-filter/issues/107#issuecomment-954215848

**Comment by philipphofmann** [comment]
I tried using path-filters in https://github.com/getsentry/sentry-cocoa/pull/3887 and it turns out it's a bit more complicated than using GH actions builtin `paths:`. As we don't have any required checks the advantage described in https://github.com/dorny/paths-filter/issues/107#issuecomment-954215848 doesn't apply to our repository. I think we can continue using  GH actions builtin `paths:` instead to optimize our CI. We can close this.
