### ISSUE TITLE
Send accessibilityIdentifier only if sendDefaultPii enabled

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2406]
### Description

The following too locations send the `accessibilityIdentifier` even if sendDefaultPii is disabled. `accessibilityIdentifier` could contain PII. Instead, we can only send the `accessibilityIdentifier` if sendDefaultPii is enabled. Please check the repository for possible other usages of `accessibilityIdentifier`.

https://github.com/getsentry/sentry-cocoa/blob/efeb69e9c50860c600d68640b1f465cc83a1a7f7/Sources/Sentry/SentryUIEventTracker.m#L130

https://github.com/getsentry/sentry-cocoa/blob/d9757459a4a288ad57b2a8348def9eb839cbe72b/Sources/Sentry/SentryBreadcrumbTracker.m#L219

**Comment by brustolin** [comment]
`accessibilityIdentifier `  is not meant to be used to store user information. Of course devs can misuse this.
Tieing this to `sendDefaultPII` will punish developers that do proper use of the property. 
Maybe they want to see the `accessibilityIdentifier` because they use it correctly, but don't want to send other types of PII.

Having only one flag that enable nothing or everything is a little problematic. 
If we really need to given devs the options I would suggest a different flag.

**Comment by kevinrenskers** [comment]
The identifier should only be something like "username" or "email" or "password", but not the actual value. I agree with @brustolin that `accessibilityIdentifier` is not meant to contain PII and it seems very weird to me to stop sending that if `sendDefaultPii` is disabled.

**Comment by philipphofmann** [comment]
Yep, that makes sense. Let's close this one because of the reasons explained above.
