### ISSUE TITLE
Crash reports not emitted when client is re-started

### ISSUE THREAD

**Issue by zachbai** [getsentry/sentry-cocoa#2419]
### Platform

macOS

### Installed

Carthage

### Version

7.6.1 (also tried bumping to latest 7.31.2, issue persists)

### Steps to Reproduce

1. Start SDK integration with `[SentrySDK startWithConfigureOptions ...]` on app startup
2. At some point during application, call `[SentrySDK close]` to stop crash reporting
3. Re-initialize the SDK integration with `[SentrySDK startWithConfigureOptions ...]`
4. Manually crash app (e.g. `[SentrySDK crash]`)
5. Observe that no crash report is omitted.

Note that if a crash is manually triggered between steps 1 and 2, a crash report is properly emitted as expected.

I also messaged the Sentry Community Discord about this but received no response (see message [here](https://discord.com/channels/621778831602221064/814577827043082250/1042518178938486844)).

Copied from my message:

> Based on a bit of digging, it looks like the state of the SentryCrash/SentryCrashWrapper is never reset after it’s [modified in close()](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryCrashWrapper.m#L59), even if SentryCrashIntegration is reinstalled (e.g. [here](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryCrashIntegration.m#L109)), as would be done when the client is re-initialized. 

### Expected Result

Crash report is emitted even after SDK is restarted.

### Actual Result

Crash report is not emitted even after SDK is restarted.

Note that this behavior is implemented properly in the Sentry Rust SDK, which we use in the same binary (our app is a native macOS app built in Rust).

**Comment by philipphofmann** [comment]
Thanks for reporting this, @zachbai. I can reproduce the problem with the latest version on our macOS-Swift and iOS-Swift sample apps.

> I also messaged the Sentry Community Discord about this but received no response (see message [here](https://discord.com/channels/621778831602221064/814577827043082250/1042518178938486844)).

Sorry about that. I totally missed your message there. We don't have many people asking questions on Discord. I'm going to check it daily now again.

**Comment by zachbai** [comment]
Thanks for taking a look!

Our use case necessarily involves restarting the SDK for all user sessions, so fixing this is relatively high priority for us.  If this isn't as high prio on your side, would it be helpful for me to take a look and draft a PR?

**Comment by brustolin** [comment]
>would it be helpful for me to take a look and draft a PR?

Very helpful!!

**Comment by philipphofmann** [comment]
This must go on a 7.x.x hotfix release and not on 8.x.x.

**Comment by kevinrenskers** [comment]
Start the SDK:

- `SentryCrashIntegration.startCrashHandler` is called
- This calls `SentryCrashInstallation.install`
- This calls `[SentryCrash sharedInstance]`, which calls `SentryCrash.init` since there is no shared instance yet
- This sets the `monitoring` property
- Then `SentryCrash.install` gets called and everything works because `monitoring` is set

So, we have a shared SentryCrash instance with `monitoring` set.

Then, we close the SDK. This sets `SentryCrash.monitoring` to `SentryCrashMonitorTypeNone`

Then we start the SDK again:

- `SentryCrashIntegration.startCrashHandler` is called
- This calls `SentryCrashInstallation.install`
- Since `[SentryCrash sharedInstance]` already exists, `SentryCrash.init` is not called
- `SentryCrash.install` gets called but `monitoring` is not set so it returns `false`

Can we delete the `SentryCrash` shared instance when we close the SDK? That would solve all of this. Or we can add `- [SentryCrash setMonitoring:]` to a class extension so we can call that from within `SentryCrashInstallation.install`: turn monitoring back on before calling `[handler install]`.

**Comment by brustolin** [comment]
> Can we delete the SentryCrash 

Yes

**Comment by kevinrenskers** [comment]
Right I know we technically can, but what are the consequences going to be? For example what's the point of setting 

```
[handler setMonitoring:SentryCrashMonitorTypeNone];
handler.onCrash = NULL;
```

If we're then getting rid of the entire handler (the shared instance of SentryCrash) anyway? As soon as *anything* would call `[SentryCrash sharedInstance]` then we're going to create a brand new instance with monitoring enabled again, even though the SDK was closed. That's not good.

So I think we need to think about what change has the least amount of side effects.

**Comment by brustolin** [comment]
I believe this `self.monitoring = SentryCrashMonitorTypeProductionSafeMinimal;` should be inside `[SentryCrash install]`
And then we fix this.

**Comment by brustolin** [comment]
Looks like `[SentryCrash install]` is already overriding the monitoring with
```
_monitoring = sentrycrash_install(self.bundleName.UTF8String, self.basePath.UTF8String);
```
Maybe the problem is inside `sentrycrash_install`

**Comment by alokedesai** [comment]
@philipphofmann @kevinrenskers Thanks for the quick fix, do you have an ETA for when this will be released? 

We're trying to determine if we should fork sentry-cocoa in the meantime given this is blocking us from receiving crash reports.

**Comment by alokedesai** [comment]
Thats's wonderful. Much appreciated!

**Comment by philipphofmann** [comment]
The release is out now @alokedesai.

**Comment by alokedesai** [comment]
We (Warp team--a Mac terminal) can confirm that we now see reports after this change. However, with this change it seems that signal handlers are not properly removed after uninit--this is the invariant we need so that we can make sure no signal handlers are passed to child processes when we start a shell process.

Is there a way to continue to keep this behavior? It's pretty critical behavior to keep for us--if the signal handlers are passed to the shell process, programs running within the shell can hang when they end up segfaulting.

**Comment by philipphofmann** [comment]
Hmm, that's weird. We restore the previous signal handlers here
https://github.com/getsentry/sentry-cocoa/blob/923362df3e96c6cb6436d749343a01832791ca7d/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_Signal.c#L197-L214

That code gets called when calling close.

What do you mean by `Is there a way to continue to keep this behavior?`?
