### ISSUE TITLE
Fix flaky testConcurrentSpansWithTimeout

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2488]
### GitHub action Run Link

testConcurrentSpansWithTimeout_disabled

### Disabling PR

https://github.com/getsentry/sentry-cocoa/pull/2487

### Description

[raw-test-output-iOS-xcode-13.2.1-os-14.5.zip](https://github.com/getsentry/sentry-cocoa/files/10153360/raw-test-output-iOS-xcode-13.2.1-os-14.5.zip)

**Comment by armcknight** [comment]
This is the double-free issue I've been seeing
```
xctest(6459,0x70000b63b000) malloc: double free for ptr 0x7fc0859e1800
xctest(6459,0x70000b63b000) malloc: *** set a breakpoint in malloc_error_break to debug

Restarting after unexpected exit, crash, or test timeout in SentryProfilerSwiftTests.testConcurrentSpansWithTimeout(); summary will include totals from previous launches.
```
I'm not convinced it's this test case or method, because it happens to other test methods adjacent to it. I bet it's more just the time this is run in the test suite with that delayed dispatch in the file manager or something like that; maybe we could try setting the option to randomize the test orders, not sure if that would help or make things more confusing 😆

**Comment by philipphofmann** [comment]
Maybe https://github.com/getsentry/sentry-cocoa/pull/2541 fixes the double free issue.
