### ISSUE TITLE
Use the source property of the SDK interface

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2625]
### Description

We need to send the packager manager used to install Sentry SDK. 
The way to do this is by using the `source` property in the SDK payload interface.

See https://github.com/getsentry/develop/pull/815

**Comment by AbhiPrasad** [comment]
Instead of using a top level `source` field, we can update the `source` in the `source:identifier` schema that is used in the packages field on the sdk interface. https://github.com/getsentry/sentry/issues/43427

In your case you would have

```
{
  "sdk": {
    "name": "sentry.cocoa",
    "version": "8.0.0",
    "packages": [
      {
        "name": "carthage:getsentry/sentry-cocoa",
        "version": "0.39.0"
      },
    ],
  }
}
```

Other names could be `spm:https://github.com/getsentry/sentry-cocoa.git` for SPM and `cocoapods:https://github.com/getsentry/sentry-cocoa.git` for Cocoapods.

Could you detect this at build time and inject them in? You could try to check for the existence of a `Podfile` or `Package.swift`.

**Comment by brustolin** [comment]
> @brustolin, do you have any ideas on how we can detect this?

Yes, by using compiler macros.

**Comment by philipphofmann** [comment]
JIRA ticket that will allow us to query this info in looker: https://getsentry.atlassian.net/browse/DATA-1575
