### ISSUE TITLE
Strange 'Redacted' statements in crash logs

### ISSUE THREAD

**Issue by caglaruslu** [getsentry/sentry-cocoa#280]
_Platform:_
-   iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
-   Yes ->  4.2
- [ ]  No

_sentry-cocoa installed with:_
-  CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.1.0**

---
I have following issue:

I use 'sentry.io' to list the crash logs. One of the logs has some strange 'redacted' statements as shown in the screenshot. I can't even tell if the log could be symbolicated by Sentry.
I did some research and found that;
https://stackoverflow.com/questions/12809174/how-to-stop-symbolicate-adding-redacted-pieces-to-ios-crash-log

So I thought the problem may be caused by Sentry.

<img width="544" alt="screen shot 2019-01-12 at 20 02 43" src="https://user-images.githubusercontent.com/30175066/51076200-518ba800-16a6-11e9-9180-f6fca6bbaf2e.png">

URL for this issue: https://sentry.io/drive-buddy-6o/dev-ios/issues/834358382/?query=is%3Aunresolved%20dist%3A3.0.1635

**Comment by d2vydov** [comment]
bump, the same problem

**Comment by fetzig** [comment]
AFAIK this only happens if 
A) crash is reported from the simulator and not a device
B) symbols are missing: haven't been uploaded to sentry. or have been uploaded after the crash report was sent to sentry.io (sadly they aren't reprocessed after a new dsym arrives).

if that's not the case, I would need more info, to verify/fix.

naturally, the sentry issue linked in the description doesn't exist anymore.

those things would help:
 * device and ios version
 * full "<redacted>" stack trace
 * full stack trace from Xcode when running on the same device in debug mode. if possible.

**Comment by Eysner** [comment]
@fetzig 
Is there any way to get crash files for processed it manually?

**Comment by philipphofmann** [comment]
@caglaruslu and @d2vydov do you still experience problems with this or is it fixed now and we can close this issue?

**Comment by philipphofmann** [comment]
@Eysner We don't really want our users to have to manually process the crash files. If you are interested in how we do this checkout [`SentryCrashReportConverter`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryCrashReportConverter.m).

**Comment by philipphofmann** [comment]
As we didn't receive new information for quite a while, we close this now.

**Comment by d2vydov** [comment]
@philipphofmann sorry for inactivity, but yeah, we are still experience problems - every crash log contains `<redacted>` symbols
this screenshot from today's crashlog: 

<img width="520" alt="Screenshot 2020-09-01 at 15 29 47" src="https://user-images.githubusercontent.com/9073024/91851520-fd14b200-ec67-11ea-9dc9-d316df081938.png">

but we are using 4.4.1 sentry, the pod is  
```
Sentry:
    :git: https://github.com/getsentry/sentry-cocoa.git
    :tag: 4.4.1
```

I will update sentry to last version and will give feedback here in a few days.

**Comment by bruno-garcia** [comment]
The server will add `<redacted>` instead of the function names when we don't have symbols available for the library that contains that code. It often happens on system symbols, once Apple releases updates and Sentry still doesn't have those debug symbols available.

Is this still happening? If so, could you please write the version of the OS that this is happening? It's in the event _Device_ section of the event detail.

**Comment by d2vydov** [comment]
we are notice these versions: iOS 13.5.1, 13.4.1, 13.6, 13.5, 13.6.1, 14.0, 13.3.1, 13.2.3, 13.5.5.

unfortunately, we got that on every crash now

**Comment by bruno-garcia** [comment]
Can you please link the project in Sentry?

**Comment by d2vydov** [comment]
> Can you please link the project in Sentry?

you can look at any project here: https://sentry.dlg.im/organizations/dialog

**Comment by bruno-garcia** [comment]
Since that's self hosted, you'd need to be loading the Apple debug symbols. I'm not sure how it works. 
At Sentry (sentry.io) we make sure to make debug symbols available when new versions come out.

@HazAT thoughts?

**Comment by philipphofmann** [comment]
@d2vydov can you please share one issue with us, so we can take a closer look?

**Comment by bruno-garcia** [comment]
I'm pretty sure this is due to missing symbols.
We collect them ourselves. On prem won't have it unless the admins do the same.

**Comment by GaoYuJian** [comment]
> I'm pretty sure this is due to missing symbols.
> We collect them ourselves. On prem won't have it unless the admins do the same.

We have some problems with the on-premise sentry,   is there a way to upload the system framework's symbol files and share with many projects?

**Comment by bruno-garcia** [comment]
I apologize but this is something we can't help you with. We open source everything we build, including software that is [able to collect system symbols Android from devices](https://github.com/getsentry/symbol-collector), [a library to symbolicate pretty much any format](https://github.com/getsentry/symbolic), but in the area of actually getting data into the symbol servers so that [symbolicator](https://github.com/getsentry/symbolicator) can work, this is something we can't provide guidance on.
