### ISSUE TITLE
Latest Version 8.3.3 still facing a lots of crashes caused by Sentry SDK

### ISSUE THREAD

**Issue by zhgchgli0718** [getsentry/sentry-cocoa#2850]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.3.3

### Steps to Reproduce

unknown, seem to be random crashes.

ref #2832

### Expected Result

The app was stable before we updated to version 7.3.1, but we're experiencing issues now.

Our current crash-free rate is around 98.X%, which is lower than our previous rate of 99.98% before we upgraded the SDK version. :(

ref #2832

### Actual Result

previous issue: #2832

We are extremely disappointed with Sentry as stability is crucial to our users and their experience.

Unfortunately, the latest version of the Sentry SDK did not address the numerous crash issues we were experiencing, and we have reverted to version 7.3.1 to maintain stability.
Upon monitoring the data after the rollback, we can confirm that the Crash-Free Rate has returned to 99.X%.

We can conclude that Sentry 8.x.x provided an unstable SDK to clients, which is absurd as crashes occurred on the service that monitors issues and crashes.

**Comment by brustolin** [comment]
Hello @zhgchgli0718 Im so sorry to hear about this. 
Right now we're focused on improving the SDK stability and to solve this problems asap.

Do you mind sharing the options you use to initialize Sentry SDK (no need to share the DSN).
Also, It would help if you could share the stack trace of one of those `EXC_BAD_ACCESS` errors mentioned in the previous PR.

**Comment by FelixHerrmann** [comment]
Hey guys! We noticed the same increase of crashes when we upgraded from Sentry 8.2.0 to 8.3.1 and 8.3.3. We had profiling enabled since it is available with no (noticeable) issues but 8.3.* seems to introduced something that is producing crashes quite frequently.

These are the most common ones:
- `KERN_INVALID_ADDRESS` in combination with `[__NSArrayM enumerateObjectsWithOptions:usingBlock:]`
- `Invalid type in JSON write ((null))`
- `-[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]`
- `-[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil`

@philipphofmann I will email you the name of our organization too to give you insights!

**Comment by brustolin** [comment]
Hello @zhgchgli0718 we are working on a few things we found out. But in order to be sure this are the things that are affecting you, it would be great if you could share your org name with us through email. Either philipp's or mine  dhiogo.brustolin@sentry.io.

**Comment by zhgchgli0718** [comment]
Thank you for letting us know that the Sentry team is actively working on resolving the issues. For now, we will stay on version 7.3.1 temporarily until more specific problems are resolved before considering an upgrade.
