### ISSUE TITLE
Enabling File IO Tracing caused the app hanging.

### ISSUE THREAD

**Issue by alexlee72** [getsentry/sentry-cocoa#3167]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.1.0 or above

### Steps to Reproduce

1. Set `enableFileIOTracing` to true
2. Open a file to read: `Data(contentsOf: fileURL)`
3. Start calling `[SentryNSDataSwizzling swizzleNSData]` to all the way to `[SentryStacktraceBuilder retrieveStacktraceFromCursor:]` on the main thread

![Screenshot 2023-07-18 at 12 46 23 PM](https://github.com/getsentry/sentry-cocoa/assets/6087667/61cd17ab-220d-440d-bb4f-cc77fcdb5fca)

### Expected Result

The swizzling methods shouldn't be blocking the main thread to make the app responsive.

### Actual Result

The swizzling methods are running on the main thread so it could make the app unresponsive when the app tried to read files many times for a short period of time.

If I disable FileIOTracing, the swizzling methods won't be called.

I'm wondering if you can call the swizzling methods on the background thread.

**Comment by philipphofmann** [comment]
We need the current stacktrace for issues like these, and we must do this on the main thread. If your app does file IO operations on the main thread, we think it's acceptable to slow it down a bit so that you can fix it. Retrieving the stacktrace on the main thread could be extremely slow before v 8.9.0. In[ 8.9.0](https://github.com/getsentry/sentry-cocoa/blob/main/CHANGELOG.md#890), we shipped stopped symbolicating stacktraces locally, which should solve your problem. Please update to at least 8.9.0. If the issue persists, please reopen this issue.

**Comment by alexlee72** [comment]
Sounds good. I found out that symbolicating stacktraces took most of the time. I guess 8.9.0 might be working with our apps as it doesn't have the function. Let me try out 8.9.0 or later.
Thanks for the reply.

**Comment by brustolin** [comment]
Just be aware that while `debug = true` in SentryOptions, we still symbolicate locally so you don't have to send the symbols of every build you do.
