### ISSUE TITLE
`IPHONEOS_DEPLOYMENT_TARGET` out of range warning

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-cocoa#3313]
### Description

Building the SDK triggers the following warning
```
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99. (in target 'SentryPrivate' from project 'Sentry')
```

**Comment by brustolin** [comment]
You're receiving this warning because of Xcode 15 support.
According to [Apple](https://developer.apple.com/ios/submit/), Xcode 14 will be deprecated April next year.

> Please note that as of April 2024 all iOS and iPadOS apps submitted to the App Store must be built with a minimum of Xcode 15 and the iOS 17 SDK.

Until then we need to support iOS 11.

**Comment by philipphofmann** [comment]
@brustolin, I guess it's worth putting that information into the [troubleshooting guide](https://docs.sentry.io/platforms/apple/troubleshooting/) of the docs. Then we can close this issue.

**Comment by brustolin** [comment]
IMO, there is nothing to "troubleshoot" about it, we don't have a solution for the warning to go away and we will have to remove from the troubleshoot page later.
We might consider closing this issue now because we know it will be resolved when we increase the minimum requirement of the SDK, or we can leave it open to be closed when we do bump the minimum requirement of the SDK.

**Comment by brustolin** [comment]
Closing it, nothing to do about it right now, the warning will disappear the next bump of iOS Version.
