### ISSUE TITLE
Crash using Sentry in an authorization plugin on macOS 14.2b1

### ISSUE THREAD

**Issue by mlink** [getsentry/sentry-cocoa#3368]
### Platform

macOS

### Installed

Swift Package Manager

### Version

8.14.2

### Steps to Reproduce

1. Use Sentry in an Authorization Plugin that installs a crash monitor.
2. Run

### Expected Result

No crash.

### Actual Result

Crashes due to EXC_GUARD at this location https://github.com/getsentry/sentry-cocoa/blob/dd0557fb0fec40f5527e4f40ead6f82e092fde0f/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_MachException.c#L490

Crash does not occur when running in a normal application.

[SecurityAgentHelper-arm64-2023-11-01-112045.txt](https://github.com/getsentry/sentry-cocoa/files/13229744/SecurityAgentHelper-arm64-2023-11-01-112045.txt)

### Are you willing to submit a PR?

Yes

**Comment by philipphofmann** [comment]
Thanks for reporting this, @mlink. Just to be on the same page, are you referring to an [Authorization Plugin](https://developer.apple.com/documentation/security/authorization_plug-ins)?

**Comment by mlink** [comment]
> Thanks for reporting this, @mlink. Just to be on the same page, are you referring to an [Authorization Plugin](https://developer.apple.com/documentation/security/authorization_plug-ins)? Did this work on a previous macOS version?

Yes, `Security.AuthorizationPlugin`. Specifically this runs in the context of login (i.e. `system.login.console`) under the `SecurityAgentHelper-<platform>` process.

Yes, it has been working on all prior versions of macOS before the 14.2b1 that was released recently.

**Comment by philipphofmann** [comment]
I see nothing related to the Authorization Plugin in the [release notes](https://developer.apple.com/documentation/macos-release-notes/macos-14_2-release-notes). As this has never happened before and currently only occurs in the beta release, I assume that Apple changed something, and it could be that it's fixed when macOS 14.2 is shipped. Therefore, we aren't willing to spend time on something that could be fixed by Apple in a couple of days. Please reopen the issue when you still see this occurring when macOS 14.2 becomes available. Thanks for reporting this, @mlink.
