### ISSUE TITLE
MetricKit reporting reports huge amount of events with no clear benefit

### ISSUE THREAD

**Issue by DenTelezhkin** [getsentry/sentry-cocoa#3392]
### Platform

macOS

### Installed

Swift Package Manager

### Version

8.14.1

### Steps to Reproduce

1. Enable MetricKit reporting
2. Deploy to production
3. Observe huge amounts of useless events

### Expected Result

MetricKit should report something useful, and in smaller amounts of events. Currently it sends so much events, that would blow any pricing plan in a very short time.

For example, just in a single day following event was reported 276000 times for just 10 users.

```
start_wqthread
New
Level: Warning
MXCPUException totalCPUTime:90 sec totalSampledTime:162.209 sec
```

![CleanShot 2023-11-09 at 13 44 20@2x](https://github.com/getsentry/sentry-cocoa/assets/853604/c2822f6c-aabc-4400-bb8f-b2a5cc913bd1)

(Actual events can be found here - but this link requires authorization https://macpaw.sentry.io/issues/4605658052/?project=5428010&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=7d&stream_index=0)

There are other events, reported in similar fashion, but this one is by far a leader.

Not only this is a huge amount of events, I can see no useful value in them it's not clear how to "fix" any of those warnings.

### Actual Result

If those events are expected to be delivered in such quantities, MetricKit integration should have some kind of spike protection, or sampling rate, because clearly analyzing 276000 events from 10 users is useless.

### Are you willing to submit a PR?

Not sure what PR would look like for this problem.

**Comment by philipphofmann** [comment]
> MetricKit should report something useful and in smaller amounts of events.

We don't have any control over how valuable the MetricKit data is. All our integration does is subscribe to the data of MetricKit and convert it to Sentry events. You can use `beforeSend` to drop events like you specified in the docs: https://docs.sentry.io/platforms/apple/configuration/metric-kit/

> You can identify MetricKit events by looking at the `mx_hang_diagnostic`, `mx_cpu_exception`, and `mx_disk_write_exception mechanism.type`.

Anyways, it seems your application is using excessive CPU time over a short period. Otherwise, MetricKit wouldn't create the event.

I checked your events, and I think we create around 15 MetricKit events with MXCPUException for a user at the same time with the same stacktrace and the same breadcrumbs. It could be that we do something wrong when converting MetricKit data.

A sample rate just for MetricKit events is something we can talk about, as I already saw the same problem for other users as well. What do you think @brustolin, @armcknight, and @kahest?

**Comment by brustolin** [comment]
> and I think we create around 15 MetricKit events with MXCPUException for a user at the same time with the same stacktrace and the same breadcrumbs

1. This needs some investigation.

> A sample rate just for MetricKit events

2. Maybe item number 1 will be enough to mitigate this, otherwise I don't see a problem with having a MetricKit sample rate.

**Comment by philipphofmann** [comment]
Okay, so just created a meaningful MXCPUException with a proper stacktrace, see https://sentry-sdks.sentry.io/share/issue/ef7dd89d872b448b87c37d820b43aa48/

![CleanShot 2023-11-09 at 14 13 50@2x](https://github.com/getsentry/sentry-cocoa/assets/2443292/1e9fa116-a166-4f19-bd94-4b48e3416ef9)

I see `start_wqthread` with a stacktrace with only one frame for multiple customers. One idea is to just drop these for now, as they don't add any value and are only expensive for our customers.

**Comment by kahest** [comment]
Does errors samplerate apply to errors we create for MetricKit events / should it?

Regardless, dropping `start_wqthread` if they're not actionable makes sense.

**Comment by philipphofmann** [comment]
I found an endless loop in an edge case. I'm going to open an PR soon.
