### ISSUE TITLE
SentryCoreDataSwizzling crashing App sometimes

### ISSUE THREAD

**Issue by tensei** [getsentry/sentry-cocoa#3454]
### Platform

iOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.16.1

### Steps to Reproduce

Calling `.save()` on `NSManagedObjectContext` crashes the App sometimes

### Expected Result

No crash

### Actual Result

Event ID: c263d6dbc17549178a9e7e09a1f0103d
![crash](https://github.com/getsentry/sentry-cocoa/assets/6447030/68b46c64-a8a4-47dd-869a-ae6bc7bc5209)

**Comment by brustolin** [comment]
Thanks for reporting this @tensei, we will look into this.

**Comment by philipphofmann** [comment]
We also see this in our [internal SDK crashes](https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved+coredata&referrer=issue-list&sort=user&statsPeriod=14d).

**Comment by realkosty** [comment]
@tensei to mitigate you can temporarily disable the feature
```
options.enableCoreDataTracing = false
```

**Comment by philipphofmann** [comment]
I looked at a couple of crashes, and I think the underlying problem is that Sentry wrongly marks `SentryCoreDataSwizzling` as inApp. So it seems like the `SentryCoreDataSwizzling` is causing the crash, but instead, the inApp frames above are the root cause. We can fix this by updating [our grouping config on the server](https://github.com/getsentry/sentry/blob/230daec21a79f805105371ae1eedd13bf300097f/src/sentry/grouping/enhancer/enhancement-configs/newstyle@2023-01-11.txt#L54-L68). I will open a PR soon.

**Comment by philipphofmann** [comment]
This will be fixed on the server with https://github.com/getsentry/sentry/issues/60515, for which I already opened a PR https://github.com/getsentry/sentry/pull/61903. No SDK changes are required.

**Comment by philipphofmann** [comment]
Backend PR merged https://github.com/getsentry/sentry/pull/61903, so we'll release this soon after CI completes.
