### ISSUE TITLE
Using Sentry to monitor customer's own SDKs used by their end users

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry-cocoa#3526]
### Problem Statement

I received the following query from a customer:

 Our product offers native, in-app experiences to simplify user journeys. While zeroing down on SDK crash and performance monitoring, Sentry seems like a good fit but we are facing roadblocks:

1. Size of Sentry's iOS SDK : The Sentry SDK inside our SDK would consume around an MB. For our merchants, a KB increase in the size of the App can lead to drop-offs, _I was planning to explore the angle of writing a  lightweight wrapper over Sentry's APIs. I would be highly obliged if your team could provide the appropriate guidance and support_
2. How can we resolve conflicts when the end user's app also uses Sentry's SDK for monitoring their own app since our SDK will also use Sentry

**Comment by armcknight** [comment]
Is this from an actual customer? I mean an app developer that uses our SDK in their app(s). It sounds like a competitor, or at least someone developing an orthogonal SDK.

In the past I've proposed breaking up the Sentry SDK into modules, and this would allow them to pick and choose the components they actually want included with their SDK, which would help with (1), but I don't think there's any priority or timeline for that work.

For (2), in general it is a bad idea to put an SDK inside another SDK, because of the dependency diamond problem ("conflicts when the end user's app also uses Sentry's SDK") that is better mitigated if they list us as a dependency in the standard package manager ecosystem; then they'd have to weak link to us and dynamically call our methods (using e.g.  `NSClassFromString`, `performSelector`, `NSInvocation` et al). But I don't think that what they want as stated is something we want to support–turning Sentry from a product into a platform is a larger discussion I haven't seen before and is outside the scope of this repo, that would need to go all the way up the food chain.

**Comment by philipphofmann** [comment]
We don't recommend that use case, see our [docs](https://docs.sentry.io/platforms/):

> It is bad practice to use Sentry SDKs in third-party plugins, packages, and libraries (such as payment SDKs or embeddable widgets) meant to be consumed by other apps. If an app uses a Sentry SDK, as well as a third-party package with its own Sentry SDK installed, then the following issues can occur:
> 
> Version conflicts.
> [Signal handlers](https://en.wikipedia.org/wiki/C_signal_handling) may overwrite each other, leading to one of the Sentry SDKs operating incorrectly.
> Third-party SDKs and libraries may leak users' PII data to the third-party's Sentry organization.

For (1): Ideally, we would split up our SDK into multiple packages, having one lightweight package with the minimum features and no crash handling, no performance, no profiling, no references to UIKit, etc. That lightweight package is also fully written in Swift, so Swift server can use it. We don't see a high enough demand to put in the effort for that. 

> I was planning to explore the angle of writing a lightweight wrapper over Sentry's APIs. I would be highly obliged if your team could provide the appropriate guidance and support

That could take some time, and I don't think we want to invest in that now. Although the lightweight SDK would only send [events](https://develop.sentry.dev/sdk/event-payloads/) as [envelopes](https://develop.sentry.dev/sdk/envelopes/), there is other nontrivial stuff as [rate limiting](https://develop.sentry.dev/sdk/rate-limiting/) or ideally offline caching.

For (2): Exactly because of that we don't recommend the use case, see ⬆️ . As already mentioned by @armcknight: 

> we want to support–turning Sentry from a product into a platform is a larger discussion

Unless we change our view on that topic as a company, I don't see this issue landing and therefore will close this for now.
