### ISSUE TITLE
SentryPrivate framework shared library gets removed during build

### ISSUE THREAD

**Issue by amattil1** [getsentry/sentry-cocoa#3622]
**Description**

Building for iOS, using Gradle Xcode plugin (https://github.com/openbakery/gradle-xcodePlugin) SentryPrivate.framework/SentryPrivate gets removed and post-process signing steps fail as required file is missing. 

Sentry.Framework and it's library is ok, and does not get removed. 

**When does the problem happen**

- [x] During build
- [ ] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: MacOS
- Compiler: Xcode 15.2, default compilers
- CMake version and config: Cmake 3.28.2

**Steps To Reproduce**

Build project that has SentryPrivate.framework embedded, with following command

xcodebuild -project xx.xcodeproj CODE_SIGNING_ALLOWED=NO  

**Log output**

No errors on log and build succeeds, but if you peek inside the final IPA, Sentry.Framework and it's dynamic library is there, byt SentryPrivate.framework/SentryPrivate is missing.

**Comment by brustolin** [comment]
@amattil1 can you share the logs of the signing step that fails? 
I believe I know what is the problem. Because we're shipping an API usage manifest as [required by Apple](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api), our Sentry framework also needs to be signed.

**Comment by amattil1** [comment]
I contacted our obfuscation product team, and they say there is a error building the framework, as SentryPrivate.framework directory gets into final IPA and that directory has PLIST file, which points to non-existing file. 

Not sure how to fix this now.

**Comment by brustolin** [comment]
Another suggestion, instead of downloading sentry code and build it yourself, is it possible to use or pre-build artefacts?

You just need to download Sentry.xcframework.zip from [here](https://github.com/getsentry/sentry-cocoa/releases/tag/8.20.0) and add Sentry.xcframework as dependency, you can ignore the two other folders in the zip.

**Comment by amattil1** [comment]
Hi, yes. That's what I did - downloaded from there. 

I got a link to sentry-cocoa branch in GH that does not use SentryPrivate.framework. I was able to build Sentry.xcframeworks using that, and it seems to work, also with out obfuscation product. 

I heard that future Sentry releases will not be having SentryPrivate.framework, so I think we can use this self-built one until those releases come out without SentryPrivate.

Thanks for the help!
