### ISSUE TITLE
snapshotStacktrace silently failing

### ISSUE THREAD

**Issue by ryan-noths** [getsentry/sentry-cocoa#371]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> Swift 5.0
- [ ]  No

_sentry-cocoa installed with:_
- [x] Swift Package Manager
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.4.3**

---
I have following issue:

`snapshotStacktrace` completion handler not being called during a send event
I now know that it was because `startCrashHandler()` was not invoked on the client beforehand but it was not clear at all as no errors were presented

The issues the arose were:
- `snapshotStackTrace` was not calling the completion handler and subsequently not sending the event

**Steps to reproduce:**
- setup `Client` as usual and do not call `startCrashHandler()`
- Send an event: 
    ```
    client.snapshotStacktrace { [weak client] in
            guard let client = client else { return }
            client.appendStacktrace(to: event)
            client.send(event: event, completion: completion)
        }
    ```

**Actual result:**
- `snapshotStacktrace` completionHandler does not get called

**Expected result:**
- An errorHandler of some kind so that the developer can handle it and correct the issue

**Comment by fetzig** [comment]
To make sure I don't waste your time: Since `snapshotStacktrace` will be dropped in 5.x, further improvement will most likely not happen. A completely backward compatible PR might still get in 4.x. 

Be that as it may, I don't know what exactly is expected. "errorHandler of some kind"...what does that mean? Throwing an exception that needs to be caught by the user/sdk-consumer is not backward compatible option, this will most likely not happen. If you mean a log message, this already happens (don't even need to activate verbose logging).

Sorry for not having better news. I hope you understand.

**Comment by fetzig** [comment]
Please elaborate if you found a case where this log message isn't showing up: https://github.com/getsentry/sentry-cocoa/blob/9198a7278273bf7051e5fe8ddf962af4e2482b00/Sources/Sentry/SentryClient.m#L506

**Comment by philipphofmann** [comment]
`snapshotStacktrace` doesn't exist anymore on 5.x and we stopped the support of 4.x. Please update to 5.x and enable [`attachStacktrace`](https://github.com/getsentry/sentry-cocoa/blob/8ea852b6f12832f469b0f9103c8ed95c2abaf2c5/Sources/Sentry/include/SentryOptions.h#L116) in the SentryOptions, if you want to have stack traces attached to your events.
