### ISSUE TITLE
Bazel Support

### ISSUE THREAD

**Issue by PutkovDimi** [getsentry/sentry-cocoa#3743]
### Problem Statement

As far as I use Bazel in my projects, it would be great Sentry to support an integration with it, like Google Crashlytics does.
To show that it's not integrated so far, I published a project:

https://github.com/PutkovDimi/Sentry-Bazel-Demo-App

Here you can test and reveal current problems 

Hope it helps :raised_hands:

**Comment by brustolin** [comment]
Hello @PutkovDimi, thanks for reaching out.

I tried the steps in your repo and I encountered no errors, although I noticed that Sentry was not included in the project. Since I'm not familiar with Bazel, I won't attempt to break it.

We will add this suggestion to our backlog and monitor the demand to support Bazel.

For everyone else coming here, if you would like us to support Bazel, please leave a like on the issue.

**Comment by PutkovDimi** [comment]
Hello! I've successfully added Sentry with Carthage, so I think the problem is with https://github.com/cgrindel/rules_swift_package_manager/issues

So the issue might be closed, thanks for the response!

**Comment by brustolin** [comment]
Perfect, thank you!
