### ISSUE TITLE
Re-entrant loadView / viewDidLoad

### ISSUE THREAD

**Issue by jleandroperez** [getsentry/sentry-cocoa#3753]
### Platform

iOS

### Installed

Swift Package Manager

### Version

8.21.0

### Steps to Reproduce

1. Setup Sentry with `PerformanceTracking` and a profilingRate of 0.5
2. Launch the app

50% of the times we launch our app, Sentry's swizzled `loadView` method invokes the `.view` property of the relevant ViewController.

This ends up triggering two `viewDidLoad` invocations in our ViewController, and is causing duplication of UI objects (+ performance degradation).

### Expected Result

No `loadView` / `viewDidLoad` duplication

### Actual Result

Our main viewController is getting x2 `viewDidLoad` invocations. Please review the screenshots below:

<img width="500" src="https://github.com/getsentry/sentry-cocoa/assets/1195260/65bba668-a7c8-4d17-b632-303404142f56">

<br><br>

<img width="500" src="https://github.com/getsentry/sentry-cocoa/assets/1195260/55ffefd0-c1e2-4786-9458-742a9c726438">

### Are you willing to submit a PR?

Of course, PR will be up shortly. Thank you =)

**Comment by bjhomer** [comment]
Specifically, the issue can be seen in the first screenshot, where `loadViewIfNeeded` is being called, and that is recursively calling into `loadViewIfNeeded` again before the view was fully loaded the first time.

**Comment by brustolin** [comment]
Hello @jleandroperez, thanks for reaching out. 
I don't see the double `viewDidLoad` in your screenshots.
I couldn't reproduce it either.
Can you explain a little bit more about your view controller setup?

**Comment by bjhomer** [comment]
Hi, I'm @jleandroperez's co-worker. Don't look for duplicate `viewDidLoad`; look for duplicate `loadViewIfNeeded`. The issue can be seen in the stack traces on the left side of the screenshot. Inside `-[DOIMainContainerViewController setChildViewController:]`, we are accessing the `.view` of a view controller for the first time. This is triggering `loadViewIfNeeded` on the view controller that was passed in (as seen in frames 30-32). That's going down into some Sentry code (`-[SentryUIApplication relevantViewControllerFromWindow:]`) which eventually ends up calling `.view` _on that same view controller that's already loading its view_. 

Since the view has not finished loading yet, `.view` is apparently still nil. So accessing the view results in it loading the view again (seen in frames 12-14 on the stack). After that view finishes loading, it will call `viewDidLoad` (as seen in frame 1). And then it will unwind back to frames 30-32, UIKit will finish loading the view, and then call `viewDidLoad` _from there_. This means that the view got loaded into memory twice.

**Comment by kahest** [comment]
Hi @bjhomer, thanks for the clarification and @jleandroperez for the PR! As noted on the PR, we'd love to find a way to automatically test this, other than we think it's ready
