### ISSUE TITLE
Sentry.framework does not support the minimum OS Version specified in the Info.plist.

### ISSUE THREAD

**Issue by saulrodeo** [getsentry/sentry-cocoa#3769]
### Platform

iOS

### Environment

TestFlight

### Installed

Swift Package Manager

### Version

8.22.2

### Did it work on previous versions?

yes but unsure which version. maybe 8.21.0

### Steps to Reproduce

1. Using XCode 15.3, create a new project and add Sentry via SPM. The minimum deployment should be iOS 17.0
2. Archive the project and validate it 

### Expected Result

Validation should succeed with no issues 

### Actual Result

The bundle {appName}.app/Frameworks/Sentry.framework does not support the minimum OS Version specified in the Info.plist.

**Comment by davemess** [comment]
+1

**Comment by brustolin** [comment]
Hello @saulrodeo thanks for reporting this. We're investigating how to solve this.
If you're in a hurry to publish your app, you can use `Sentry-Dynamic` instead of `Sentry` 

Like in the images:
![image](https://github.com/getsentry/sentry-cocoa/assets/28265868/face311c-4962-4f99-91ab-409e0894c5a6)

![image](https://github.com/getsentry/sentry-cocoa/assets/28265868/e31ddb22-430d-40ee-920a-42acfee055f3)

Sorry about the inconvenience.

**Comment by zackify** [comment]
Apple strikes again, randomly enforcing some new check when I've been using xcode 15.3 for over a week lol...

**Comment by JohanAlbrectsen** [comment]
+1

**Comment by kahest** [comment]
This is likely related: https://github.com/singular-labs/Singular-iOS-SDK/issues/55 - we'll investigate workarounds.

**Comment by brustolin** [comment]
We have an alpha release that fix this issue.
Please try it and give us your feedback.
https://github.com/getsentry/sentry-cocoa/releases/tag/8.22.3-beta.0
