### ISSUE TITLE
new iOS App Store Privacy Guidelines issue (System boot time APIs usage)

### ISSUE THREAD

**Issue by jtabraham123** [getsentry/sentry-cocoa#3775]
### Problem Statement

iOS App store guidelines that take in effect May 1st prevent applications from making calls to system boot time apis (like mach_absolute_time() and systemUptime) without declaring a reason in a privacy manifest file https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api. mach_absolute_time() is used in SentryTime.mm line 30. Their "acceptable reasons for using System Boot Time apis" list make it seem like you are not allowed to send this information without the user explicitly accepting they consent to this information being sent in a bug report. I dont want my app to make the user accept a message everytime I want to send something to sentry. You are allowed to send it if "There is an exception for information about the amount of time that has elapsed between events that occurred within the app, which may be sent off-device." But im not sure if you can send the boot time directly, just using it to calculate the elapsed time and sending that seems to be allowed

### Solution Brainstorm

- Give the option to the user to disable the sending of boot time in the options object in SentrySDK.start {}
- remove the api call? - seems like this would be harder to do

### Are you willing to submit a PR?

Yes I can submit a quick PR for this, it seems semi easy to fix

**Comment by philipphofmann** [comment]
Thanks for bringing this up @jtabraham123 😃.

We already declared 35F9.1 in our `PrivacyInfo.xcprivacy`:

https://github.com/getsentry/sentry-cocoa/blob/fa409feccbfc87427acf396bfce16cac97df3640/Sources/Resources/PrivacyInfo.xcprivacy#L55-L60

[Apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394):
> 35F9.1
> Declare this reason to access the system boot time in order to measure the amount of time that has elapsed between events that occurred within the app or to perform calculations to enable timers.
> 
> Information accessed for this reason, or any derived information, may not be sent off-device. There is an exception for information about the amount of time that has elapsed between events that occurred within the app, which may be sent off-device.

We use `systemUptime` and `mach_absolute_time()` only for events that occurred within the app. In that case, we are allowed to send this information off-device. Therefore, we can keep using these APIs.

**Comment by johnhatvani** [comment]
@philipphofmann is there a timeline for when 8.22.3 will be released? (from what I can see these changes were captured in 8.22.3-beta)

**Comment by brustolin** [comment]
@johnhatvani, we will release it today.

**Comment by kahest** [comment]
@johnhatvani we added the privacy manifest stating the required API usages and reasons for this in version 8.11.0 of the SDK: https://github.com/getsentry/sentry-cocoa/pull/3259
The latest additions to the privacy manifest have been shipped with 8.21.0. We have no pending changes currently.

**Comment by armcknight** [comment]
It was just brought to my attention that we are in fact transmitting the boot time of the device, which is explicitly disallowed. We can access the boot time since we provide that manifest key, but it can also be used for calculations, the results of which we _are_ allowed to transmit, but we are not allowed to transmit the boot time itself. 

We're going to need to remove at least this line of code and make sure it's not in any other transmissions:
https://github.com/getsentry/sentry-cocoa/blob/704d854b6da5c32e7b4474dfb4cfacef7f569218/Sources/Sentry/SentryAppState.m#L114-L115

I imagine the backend implications of this are small but I'm not sure.

We are gathering this boot time via `sysctl` with the options `CTL_KERN`/`KERN_BOOTTIME`, which, while not explicitly mentioned in the letter of the docs, I believe is covered in spirit, and we should make a good faith effort to comply.

From https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394: 
> 35F9.1
Declare this reason to *access the system boot time in order to measure the amount of time that has elapsed between events* that occurred within the app or to perform calculations to enable timers.
Information accessed for this reason, or any derived information, *may not be sent off-device*. There is an *exception for information about the amount of time that has elapsed between events* that occurred within the app, which may be sent off-device.

**Comment by armcknight** [comment]
Ah, I had the wrong spot. I think the one in SentryAppState is not being transmitted. It's this one: https://github.com/getsentry/sentry-cocoa/blob/704d854b6da5c32e7b4474dfb4cfacef7f569218/Sources/Sentry/SentryCrashWrapper.m#L179

which is retrieved using `sysctlbyname` with `kern.boottime`.

**Comment by philipphofmann** [comment]
This was fixed with #3912 and #3916. We can close this now.
