### ISSUE TITLE
Is there any plan to support Vapor framework in Swift?

### ISSUE THREAD

**Issue by ladiesman218** [getsentry/sentry-cocoa#3776]
### Problem Statement

I saw Sentry now supports Apple's platforms(iOS, macOS, etc) but Swift is an open source language and could be used to build backend services. There are a bunch of frameworks designed to do this, Vapor is probably the most popular one among the community.
Could you add official SDK to support frameworks like Vapor?

### Product Area

Unknown

**Comment by brustolin** [comment]
Hello @ladiesman218, thank you for reaching out. 

In order to support Vapor, or any other Swift-only project, we need to have a Swift-only SDK. Right now, we don't have a plan to work on this, but since we started to add Swift code into our SDK, I believe that eventually, this will be a possibility, although not in the near future.

**Comment by chadwhitacre** [comment]
@ladiesman218 [Here are the docs](https://develop.sentry.dev/sdk/overview/) if you want to be the one to start a community-supported Swift/Vapor SDK. 😁
