### ISSUE TITLE
PrivacyInfo is not included in Swift Package

### ISSUE THREAD

**Issue by joshuatbrown** [getsentry/sentry-cocoa#3853]
### Platform

iOS, iPadOS

### Environment

TestFlight

### Installed

Swift Package Manager

### Version

8.23.0

### Did it work on previous versions?

no

### Steps to Reproduce

1. Include Sentry 8.23.0 as a Package Dependency in an Xcode project
2. Build and upload to TestFlight

### Expected Result

No email from Apple with issues

### Actual Result

Email from Apple with the following issue:

ITMS-91053: Missing API declaration - Your app’s code in the “Nos” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp.

---

We're using multiple third-party Swift Packages, but this appears to be from Sentry based on a scan using Wooder's handy [ios_17_required_reason_api_scanner](https://github.com/Wooder/ios_17_required_reason_api_scanner). The output from the binary scanner looks like this:

```
Analyzing binaries: ./Nos Dev.app/Nos Dev ./Sentry.framework/Sentry ./Nos Dev.app/Frameworks/Sentry.framework/Sentry
---
Used symbols in binary ./Nos Dev.app/Nos Dev: NSFileCreationDate, NSFileModificationDate, NSURLContentModificationDateKey, NSURLCreationDateKey, NSUserDefaults, stat
Used symbols in binary ./Sentry.framework/Sentry: NSFileCreationDate, stat
```

I know Sentry has a PrivacyInfo.xcprivacy file, and it seems to be included in CocoaPods distribution. Perhaps it was just missed in the Swift Package Manager package?

### Are you willing to submit a PR?

sure

**Comment by kahest** [comment]
Hey @joshuatbrown thanks for writing in - this should already work for SPM as well - we'll need to take a look. cc @brustolin

**Comment by brustolin** [comment]
Hello @joshuatbrown, thanks for reaching out. 
Our `PrivacyInfo.xcprivacy` is include for SPM too, since we are distributing a pre-compiled framework, the file goes inside the framework.

I tested `Wooder's handy [ios_17_required_reason_api_scanner](https://github.com/Wooder/ios_17_required_reason_api_scanner)` (thanks for the tip), and after reading its code I could check that it only shows which APIs are being used, but it does not check for a `PrivacyInfo.xcprivacy` and/or whether the required reason is included in privacy file. 

If you believe I got something wrong just let me know and we re-open this issue.

**Comment by bddq** [comment]
Privacy report for Sentry SDK (8.24.0) is not included when generating a privacy report from Xcode organizer with Xcode 15.2, but when the same app is built with Xcode 15.3, report is included when generating report from organizer.

Hope that helps.
Benoit

**Comment by brustolin** [comment]
Hello @bddq, If I got this right, according to Apple [documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests?language=objc), the `Generate Privacy Report` function "describe the data your app or third-party SDK collects", not related to the Api Usage.

**Comment by bddq** [comment]
Thanks @brustolin for your answer. The `Generate Privacy Report` function can show us all privacy declarations for an app and its dependencies like Sentry.

AppStore Connect mentioned me: 
> Your app’s code in the “My App” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategorySystemBootTime.

SystemBootTime is one API usage defined in your Privacy manifest, but because I built the app using Xcode 15.2, your manifest wasn't combined with MyApp one. The manifest merge with build is working with Xcode 15.3.

I just advise to use Xcode 15.3 to build an app with Sentry SDK to make sure the Privacy manifest provided by Sentry SDK is correctly merged with the mandatory manifest in the host app.
