### ISSUE TITLE
SPM won't update any packages due to Sentry

### ISSUE THREAD

**Issue by brzzdev** [getsentry/sentry-cocoa#3885]
### Platform

macOS

### Environment

Production

### Installed

Swift Package Manager

### Version

8.21.0

### Steps to Reproduce

Xcode -> File -> Packages -> Update to Latest Package Versions

### Expected Result

Packages update without issue

### Actual Result

<img width="237" alt="image" src="https://github.com/getsentry/sentry-cocoa/assets/15687450/2eefd55f-6d54-4630-bb94-6cd1a66e3f29">

`github.com: https://github.com/getsentry/sentry-cocoa: An unknown error occurred. path to reference 'refs/heads/armcknight/feat/3555-continuous-profiling/4-refactors/1-timeseries-functions' collides with existing one (-1)`

I'm not interacting with that reference at all, but maybe something's gone wrong with the repo around that branch?

Is this just a me issue?

Locked to `8.21.0` currently but also happens if I unpin

**Comment by brustolin** [comment]
Hello @brzzdev, thanks for reaching out. 
This is new for us; I can reproduce it. 
Instead of trying to update it, can you try deleting it and then adding the latest version we have available?

**Comment by brzzdev** [comment]
Hi,

You **_can_** reproduce it?

Changing the pin to `from: "8.24.0"` or `exact: "8.24.0"` don't seem to help, and I'd like to stay on `8.21.0` if possible.

I have a workaround to update my packages for now, which is removing all references to Sentry in my Package.swift, updating the other packages, and then adding Sentry back in.

**Comment by brzzdev** [comment]
I also tried that along with deleting all the SPM caches (unless I'm missing any)
`~/Library/Caches/org.swift.swiftpm`
`~/Library/org.swift.swiftpm`
`~/Library/Developer/Xcode/DerivedData/AppName/SourcePackages/checkouts/`
`~/Library/Developer/Xcode/DerivedData/AppName/SourcePackages/repositories/`
`.build` in my App directory

**Comment by brustolin** [comment]
Sorry, I can't reproduce it.

**Comment by kahest** [comment]
Hey @brzzdev this is very curious and shouldn't happen, not sure what goes on inside of SPM here.

I'm not able to repro this in a new app, and since you mentioned you already cleared all kinds of SPM caches, I'm not sure the following will help, but can you try

`$ cd ~/Library/Developer/Xcode/DerivedData/<AppName>/SourcePackages/checkouts/sentry-cocoa && swift package purge-cache`

As for the root cause - it seems there's an active branch in a sub-"directory" of a previously deleted branch (e.g. `/A/B` was deleted and a new branch `/A/B/C` was later created). Your local refs are probably messed up because of this, though, again, I'm not sure what SPM tries to do with those branches.

**Comment by brzzdev** [comment]
That seems to have resolved this issue, thanks!

Super weird though because you'd have thought completely deleting that folder would have the same effect as purging the cache. Maybe there's a cache somewhere else I missed.

Appreciate the help regardless.
