### ISSUE TITLE
Calling initializer to cause global side-effect is not very swifty

### ISSUE THREAD

**Issue by ahti** [getsentry/sentry-cocoa#432]
I just had time to have a look at the 5.0 beta. Overall I like the simplification of the API, but having the initialization of the shared client instance happen through a call to an initializer looks very weird to me. I would expect most or all initializers to be free of side-effects. Seeing the result of an initializer be discarded immediately looks very much non-idiomatic.

Since the side-effect is the only thing this operation is actually doing (as opposed to initializing and returning an instance to be used by the caller), a static function would be much more appropriate here.

So effectively, I'm proposing this:

```
 _ = SentrySDK(options: [
    "dsn": "___PUBLIC_DSN___",
    "debug": true
])
```

should instead turn into this:

```
SentrySDK.initialize(options: [
    "dsn": "___PUBLIC_DSN___",
    "debug": true
])
```

(I'm not really concerned about the method name, setUp or install could work just as well)

**Comment by philipphofmann** [comment]
Thanks, @ahti for pointing out this issue. We agree with you that the constructor having side-effects is not the cleanest way of initializing the SDK.
We have doubts naming the method `initialize` because you might mix it up with [`NSObject.initialize()`](https://developer.apple.com/documentation/objectivec/nsobject/1418639-initialize).

Currently, we are leaning towards"
`Sentry.with(options: [ ... ]);`

Other options to consider:

```
Sentry.start(options: [ ... ]);
Sentry.initialize(options: [ ... ]);
Sentry.configure(options: [ ... ]);
```

all those are "far" from how we init the Sentry SDKs in other languages.

Check out our PR https://github.com/getsentry/sentry-cocoa/pull/441 for more details.
