### ISSUE TITLE
Rework upload symbol script

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#4328]
### Description

We currently require an auth token to be provided, and caution against committing the patch to apply to get the symbol upload script to avoid committing auth tokens to the repo: 

- https://github.com/getsentry/sentry-cocoa/blob/e1c38196160220f9d7580685802a1b2a5b580c29/develop-docs/README.md?plain=1#L86-L93
- https://github.com/getsentry/sentry-cocoa/blob/e1c38196160220f9d7580685802a1b2a5b580c29/scripts/upload-dsyms-with-xcode-build-phase.sh#L4-L7

This can now be done using environment variables, so we should rework the script and leave it in the build phases. See the script I wrote for the SE iOS demo: https://github.com/sentry-demos/ios/blob/master/upload-symbols.sh

Ideally, we create a new build config for debug builds that upload symbols. This way, we don't upload a large volume from the standard debug config. We can also configure it to always upload for release builds.

This way developers can freely upload symbols as needed with minimal changes to the git working index.

**Comment by philipphofmann** [comment]
@armcknight, do you use the `upload-dsyms-with-xcode-build-phase.sh`? I created this some time ago because I regularly upload the dSYMs via Xcode. Nowadays, I always check symbolication via TestFlight and have even forgotten that this script exists. @brustolin also never uses it. My point is if none of us use it, we don't need to improve it, and we can even discuss removing it.

**Comment by armcknight** [comment]
Yep, that's fair too, we could consider removing it. It's been a long time since I needed something symbolicated for testing while debugging.

**Comment by philipphofmann** [comment]
Excellent. I removed it: https://github.com/getsentry/sentry-cocoa/pull/4398.
