### ISSUE TITLE
Expose transport on Client

### ISSUE THREAD

**Issue by rabbitinspace** [getsentry/sentry-cocoa#433]
_Platform:_
- iOS

_Swift:_
- Yes -> 5.1

_sentry-cocoa installed with:_
- Carthage

Version of sentry-cocoa:
**5.0.0-beta.2**

---

`Client` does not expose it's `transport` property, so it's not possible to, for example, set `shouldQueueEvent` handler for `SentryHttpTransport` without manually initializing a transport. 

There's `TransportInitializer` to initialize default transport but it's not straightforward to use because it depends on `Options` and `Options` is used to provide a transport to the SDK. Basically, you need to have 2 instances of `Options` object which is error-prone:

1. To initialize the transport
2. To provide transport to `SentrySDK`

**Comment by bruno-garcia** [comment]
`shouldQueueEvent` isn't really designed to be public API. Can we discuss your use case?

The unified SDK design has a callback so that user code can decide whether an event should be sent to Sentry or not. [It's called `BeforeSend`](https://docs.sentry.io/data-management/sensitive-data/#custom-event-processing-in-the-sdk). Would this solve your problem?

**Comment by rabbitinspace** [comment]
Ah, sorry, I forgot to include the reason why we're using `shouldQueueEvent` in 4.x 🤦‍♂️. 

At some point in the past we noticed that some crashlogs doesn't appear on Sentry. After investigation, we figured out that these events had a large payload (>200kb iirc, but I'm not sure). When the SDK was trying to send these events, it was receiving HTTP 4xx errors and evens were basically discarded. To work around this, we're using `shouldQueueEvent` to monitor 4xx responses and slim down events by discarding unrelated stack traces and other metadata and to re-send them. 

I don't think we can use `BeforeSend` to solve the issue because we don't know payload size until it's serialized as well as actual size limits and we don't want to slim down events when it's not necessary because it may potentially affect crashlogs quality.

**Comment by philipphofmann** [comment]
As already pointed out `shouldQueueEvent` isn't designed to be public. We are currently doing many changes to `SentryHttpTransport` and it is not guaranteed, that `shouldQueueEvent` stays there.

You pointed out that you discard stack traces and other metadata `shouldQueueEvent` if you get HTTP 4xx errors. In `BeforeSend` you have access to the `stacktrace` and you could already discard unrelated stack traces there. Maybe you can do more investigations which properties of the `Event` blow up your payload size and also clean them during 'BeforeSend'.

Another option would be to use [`TransportOptions`](https://docs.sentry.io/error-reporting/configuration/?platform=aspnetcore#transport-options) to implement your own `transport` to customize how events get sent to Sentry. You can set your own transport implementation with [`SentryOptions`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryOptions.m#L127). The problem is that this is a lot of work.

**Comment by rabbitinspace** [comment]
Thanks!

I'll investigate the suggested options and will close the issue.
Again, thanks for the help!
