### ISSUE TITLE
Change rate limiting logs to level warning or error

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#4456]
### Description

See https://github.com/getsentry/team-mobile/issues/195.

**Comment by rwachtler** [comment]
Hey @philipphofmann ! I was wondering if the goal is just to update the log-level [here](https://github.com/getsentry/sentry-cocoa/blob/main/Sources/Sentry/SentryHttpTransport.m#L127) to something like `SENTRY_LOG_WARN(@"RateLimit is active for all envelope items.")` (as the title of this issue states) or also have some additional log statement, which isn't bound to the condition that all items has to be rate-limited in order to print the log?

**Comment by philipphofmann** [comment]
I think we should also log a warning here to communicate that one envelope item of the envelope was dropped. https://github.com/getsentry/sentry-cocoa/blob/fc350a451fe35646984e94b69ada9e6d0544e022/Sources/Sentry/SentryHttpTransport.m#L229-L237

Yes, feel free to open a PR, @rwachtler. We will help you to merge it.
