### ISSUE TITLE
SentryFramesTracker.reportNewFrame acquires lock on the main thread

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#4466]
### Description

`SentryFramesTracker.reportNewFrame` frequently gets called on the main thread and it acquires a lock to report to its listeners that a new frame was reported. We must remove this lock.
https://github.com/getsentry/sentry-cocoa/blob/750f4d7b3e47b3ebcd3214c23e6bd6cc56f2914f/Sources/Sentry/SentryFramesTracker.m#L257-L269

**Comment by jasconius** [comment]
hi..... user here... I am currently experiencing *some* kind of performance issue that I think might be related to this. I can see reportNewFrame eating up something on my main thread... its not terrible but on ancient hardware (which is half my enterprise fleet) it seems to tip toward noticeable....

is there anything I can do as a user to perhaps disable this feature while this is worked on...

**Comment by philipphofmann** [comment]
>  I can see reportNewFrame eating up something on my main thread

Can you elaborate? How do you notice this? Maybe it's something else than this lock because I don't think it has a considerable impact, but you never know.

@jasconius, you have to disable [tracing](https://docs.sentry.io/platforms/apple/tracing/) and ensure you're not using `enableAppHangTrackingV2` to disable the frames tracker. Otherwise, it will run.

**Comment by jasconius** [comment]
@philipphofmann sure... some background may be appropriate... and I concede that this may ultimately be some other issue but I do believe the sentry SDK is involved...

recently upgraded enterprise application from sentry 8.21.0 to 8.37.0

users soon reported, with video evidence, that application performance had degraded substantially on older hardware (iPhone 8 Plus), user interface interaction noticeably slow with basic interactions taking a few seconds to complete, along with noticeably degraded battery life in the field (these work phones run this app basically all day)

unable to replicate on iPhone 11

i could see in the basic Xcode performance monitor that it felt something in the application was keeping an entire core busy forever...

took it to instruments, noticed `SentryFramesTracker.reportNewFrame` and `SentryFramesTracker.displayLinkCallback` getting called a lot while the application was idling along with a few other Sentry method signatures

was unable to successfully rollback sentry version to 8.21.0 because cocoapods things....

started digging on these sentry method signatures and found a link between them and use of a class in CoreAnimation called CADisplayLink

I had a single CADisplayLink running deep on the bowels of my application with default settings. I reduced this CADisplayLink's framerate from default to 4 frames per second, published a test build, two separate users reported noticeable improvement in application performance.

This application gets updated on a pretty regular basis, so I don't think this is some Apple-related change to the runtime or OS behavior that produced this effect. Attentive users were able to (without their knowledge) point to the exact version where Sentry got upgraded as the start of their troubles.

I've attached a screenshot of Instruments on the build with the CADisplayLink reduced framerate.... as you can see here on paper it doesn't seem like Sentry is guilty of very much... my theory however is that the overhead of doing whatever Sentry is doing here is keeping a core awake forever, which in turn is putting these older devices in a critical thermal state and everything just falls apart until users notice it takes them 10 seconds to snap a photo with their camera

The reason I came here is I could observe that while reducing the framerate appears to have done *something* for user experience, I suspect that there is still some performance degradation, particularly with battery life. The extra frustrating thing  is that I've been unable to successfully roll back Sentry to do a comparative analysis to see if this same Instruments result was going on with 8.21.0

![Image](https://github.com/user-attachments/assets/ec206239-5806-47c5-bacd-5ab69ed14d48)
