### ISSUE TITLE
Are SentryRateLimitParser and SentryEnvelopeRateLimit intended to be public?

### ISSUE THREAD

**Issue by rabbitinspace** [getsentry/sentry-cocoa#477]
_Platform:_
- [x]  iOS

_Swift:_
- [x]  Yes -> 5.1

_sentry-cocoa installed with:_
- [x] Carthage

Version of sentry-cocoa:
**5.0.0-beta.7**

---

There's a `SentryHttpTransport` class which requires `id<SentryRateLimits>` and `SentryEnvelopeRateLimit` objects for itself to be instantiated. There's also default implementation of `SentryRateLimits` protocol: `SentryDefaultRateLimits`.

There're two issues which prevents `SentryHttpTransport` to be instantiated outside of the framework right now (with default rate limits):

1. `SentryDefaultRateLimits` public class requires an instance of `SentryRetryAfterHeaderParser` to be instantiated but `SentryRetryAfterHeaderParser` is not in public headers.
2. `SentryEnvelopeRateLimit` class is not in public headers but it's required to instantiate `SentryHttpTransport` public class.

So, the question is:
Are the `SentryRetryAfterHeaderParser` and `SentryEnvelopeRateLimit` classes intended to be public? Or will `SentryHttpTransport` accept protocols for rate limiting?

**Comment by bruno-garcia** [comment]
We don't plan to make those types public at this time since there's too much complexity to get the actual HTTP transport to Sentry using envelopes working correctly.That said, we've removed (temporarily) a way to replace the transport from the SDK ( See #490 ). We'll add a way to replace a transport as it's part of our API in a way you can decorate the transport with your custom logic but still add our built-in transport at the end. This will come as a minor release of the SDK.

**Comment by rabbitinspace** [comment]
Thanks for the response!
I'll leave the issue open until that version of SDK is released.

**Comment by philipphofmann** [comment]
Both classes are not public anymore with 6.x.x, so we consider this issue to be resolved. We have plans to make `SentryHttpTransport` public again in the future, but we don't know yet when. Please open up another issue if you need `SentryTransport` to be public.
