### ISSUE TITLE
Callback after SDK sent event 

### ISSUE THREAD

**Issue by jkmassel** [getsentry/sentry-cocoa#660]
_Platform:_
- [x]  iOS
- [x]  tvOS
- [x]  MacOS
- [x]  watchOS

_Swift:_
- [x]  Yes -> any
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [x] Carthage
- [x] Manually

Version of sentry-cocoa:
**5.2.0**

---
I have following issue:

We're unable to manually send requests and wait for a callback, which we use to receive crash reports for crash-on-launch bugs.

**Steps to reproduce:**
In v4.xx I could write:

```swift
Client.shared.sendEvent(event: event) { _ in
  // do stuff after it's sent
}
```

**Actual result:**
In the Sentry v5.xx this is no longer possible.

**Expected result:**
We'd expect to still be able to do this, as we can't upgrade to the Sentry v5 library without it.

**Comment by philipphofmann** [comment]
Hi @jkmassel, thanks for reaching out to us. The before send was moved to the [`SentryOptions`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/include/SentryOptions.h#L75). You can use it like this:
```
SentrySDK.start { options in
    options.dsn = "your dsn"
    options.beforeSend = { event in
        return event
    }
    // ...
}
```
For an example check out: https://github.com/getsentry/sentry-cocoa/blob/master/Samples/iOS-Swift/iOS-Swift/AppDelegate.swift#L9-L19

**Comment by jkmassel** [comment]
Hi @philipphofmann – unfortunately that doesn't really address my issue – we're ok with the `beforeSend` hook, what we're missing is the `sendEvent` callback. For example, in Sentry v4 we do this:

https://github.com/wordpress-mobile/WordPress-iOS/blob/0a2ca4d11cf08310f0e0b1cd79a4e70cab8cbcc0/WordPress/Classes/Utility/Logging/SentryStartupEvent.swift#L76-L80

But in Sentry v5, as far as I can tell, that's no longer possible as there's no callback when manually sending an event. This is a blocker for us to update.

**Comment by philipphofmann** [comment]
The [`SentryClient`](https://github.com/getsentry/sentry-cocoa/blob/master/Sources/Sentry/SentryClient.m#L122-L124) calls the `beforeSend` hook of the `SentryOptions` before sending an event. You can also manually initialize a `SentryClient` and pass `SentryOptions` into it. Does this help you to achieve what you desire?

Maybe these resources help you to understand the concept better:
* https://docs.sentry.io/error-reporting/configuration/#hooks
* https://develop.sentry.dev/sdk/unified-api/#event-pipeline

**Comment by ainopara** [comment]
We have the same issue, beforeSend called before the `transport` received the event, but we want to know how many events are dropped by `transport`, and we may want to resend some events if they are dropped because there is a temporary network issue in user's device.
that means we need a callback when transport decided to drop an event, which is not the timing beforeSend is called.

**Comment by philipphofmann** [comment]
Hi @ainopara, 
we don't drop any events if there is a network issue with the user's device. When the device is offline we keep the event on the disk. If there are more than 10 events on the disk we drop the oldest one. Starting from v 5.0.0 and above we also drop events directly on the phone if you reached your rate limit. We do this because the backend would drop it anyway and we want to disburden our backend: https://docs.sentry.io/accounts/quotas/#limiting-events

What do you wish to do with the callback in the transport? If you go into more detail maybe I can suggest a different solution.

**Comment by jkmassel** [comment]
> The SentryClient calls the beforeSend hook of the SentryOptions before sending an event. You can also manually initialize a SentryClient and pass SentryOptions into it. Does this help you to achieve what you desire?

No – we need to a hook for _after_ a given event has been sent, not before.

**Comment by philipphofmann** [comment]
I'm sorry, we currently don't have such a feature in any of our SDKs, but we hear this multiple times. So this would be a feature request then. Can you maybe make a suggestion on how you wish the feature should look like?

**Comment by jkmassel** [comment]
It'd be great if it just worked the same as v4 – it allowed us to send events with a completion handler:

https://github.com/getsentry/sentry-cocoa/blob/fb4b4be84ae61f9e306348a65600c9dd93977e6f/Sources/Sentry/SentryClient.m#L228-L230

**Comment by philipphofmann** [comment]
Hi @jkmassel, sorry for the late response. We were quite busy releasing `6.0.0-alpha.0`. I see your point, we have adding this callback on our todo list. I can't make any promises on the ETA though.

**Comment by philipphofmann** [comment]
Hey, @jkmassel, according to your [Podfile](https://github.com/wordpress-mobile/WordPress-iOS/blob/ddbaa60761a136a8c2b7f910b8cc7cea0a59e72c/Podfile.lock#L433), you already upgraded Sentry to `6.2.1`. Do you still need this feature?

What about you, @shiki and @mokagio, are you still blocked?

**Comment by mokagio** [comment]
Hey @philipphofmann 👋 @jkmassel and I work on the same on the infrastructure for the WordPress and other Automattic apps. 

We ended up replicating part of that functionality by ourselves in order to migrate from 4.x to 6.x. Still, having native SDK support of some kind of "after send" hook would be very much appreciated 😄

**Comment by mokagio** [comment]
Regarding whether I'm still blocked, which I'm guessing is because of the title of the issue in which I mentioned this one (https://github.com/Automattic/Automattic-Tracks-iOS/issues/181), the answer is yes, but only tangentially relates to this one.

I opened a new issue about it #1451. Thank you for following up @philipphofmann 👍

**Comment by philipphofmann** [comment]
@jkmassel and @mokagio, do you want to do something with the event after the SDK sent it to Sentry? As far as I understand, do you want to make sure the SDK sends the event to Sentry for crash-on-launch bugs?

We had already had discussions about a similar feature. When there is a crash block, the SDK init until the SDK sends the crash report to Sentry. In such a case it would be fine to slow down the app start because there is a crash.

**Comment by philipphofmann** [comment]
Related to 
* https://github.com/getsentry/sentry-javascript/issues/2939
* https://github.com/getsentry/sentry-dart/issues/352

**Comment by philipphofmann** [comment]
@jkmassel and @mokagio, can you please reply to[ my question](https://github.com/getsentry/sentry-cocoa/issues/660#issuecomment-968930134) above ⬆️

**Comment by philipphofmann** [comment]
@jkmassel would https://github.com/getsentry/sentry-cocoa/issues/316 solve your problem?
