### ISSUE TITLE
Failed to extract arm64 for Sentry.framework

### ISSUE THREAD

**Issue by jamesncl** [getsentry/sentry-cocoa#818]
I'm trying to add Sentry to my watchOS 7.0 application.

I've added the relevant pod to my podfile:

```
target 'watchos Extension' do
  platform :watchos, '7.0'
  use_frameworks!
  enable_bitcode_for_prebuilt_frameworks!

  # Sentry
  pod 'Sentry'
end
```

My project builds successfully, however when deploying to a real device I get a build error:

> fatal error: lipo: -extract arm64 specified but fat file: /Users/james/Library/Developer/Xcode/DerivedData/Runner-ecnnxqjffpozscgwkiujttvopvcf/Build/Products/Debug-iphoneos/Runner.app/Watch/watchos.app/PlugIns/watchos Extension.appex/Frameworks/Sentry.framework/Sentry does not contain that architecture
>
> Failed to extract arm64 for /Users/james/Library/Developer/Xcode/DerivedData/Runner-ecnnxqjffpozscgwkiujttvopvcf/Build/Products/Debug-iphoneos/Runner.app/Watch/watchos.app/PlugIns/watchos Extension.appex/Frameworks/Sentry.framework/Sentry. Running lipo -info:
>
> Architectures in the fat file: /Users/james/Library/Developer/Xcode/DerivedData/Runner-ecnnxqjffpozscgwkiujttvopvcf/Build/Products/Debug-iphoneos/Runner.app/Watch/watchos.app/PlugIns/watchos Extension.appex/Frameworks/Sentry.framework/Sentry are: armv7k arm64_32 

It's complaining that it can't extract the `arm64` architecture, and that it can only find `armv7k` and `arm64_32`. Is this a bug in how Sentry is distributed or am I doing something wrong? I'm using xcode 12.0.1

**Comment by bruno-garcia** [comment]
What version of the Sentry SDK? Does this happen on the latest? We fixed some issues with packaging in recent versions.

**Comment by philipphofmann** [comment]
Hi @jamesncl, thanks for reporting this issue. 
This issue occurs because the build for Carthage fails on Xcode 12, see https://github.com/Carthage/Carthage/issues/3019. We use the recommended workaround script they recommend, which has the limitation of removing arm64 simulator architecture from compiled framework, so frameworks compiled using it cannot be used on Macs running Apple Silicon. For more info see: https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md. I'm sorry there is not much we can do until Carthage fixes this issue. 

We are going to add this somewhere to our docs.
