### ISSUE TITLE
OOM Crashes not being reported?

### ISSUE THREAD

**Issue by dannyhertz** [getsentry/sentry-cocoa#897]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version?  (5)
- [ ]  No

_sentry-cocoa installed with:_
- [x] Swift Package Manager
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**6.0.12*

---
I have following issue:

OOM crashes are not being reported!

Description goes here ...

**Steps to reproduce:**
- Crash app from OOM incident

**Actual result:**
- No reporting in dashboard

**Expected result:**
- I expect to see the OOM crash

**Comment by philipphofmann** [comment]
Hi @dannyhertz, 
Sadly, we currently don't report OOM (https://github.com/kstenerud/KSCrash/issues/10) or memory leaks (https://github.com/getsentry/sentry-cocoa/issues/315 and https://github.com/getsentry/sentry-react-native/issues/252), because they are really hard to detect. We have a breadcrumb for low memory warnings; see https://github.com/getsentry/sentry-cocoa/blob/ef362d3323de4adf388f47a6647d14e62cb171d1/Sources/Sentry/SentryBreadcrumbTracker.m#L51-L57.

Still, there could be a possibility to get some information out of [MetricKit](https://developer.apple.com/documentation/metrickit/mxhangdiagnostic?language=objc). We could also find a way to track retain cycles as mentioned here: https://medium.com/compass-true-north/the-case-of-ios-oom-crashes-at-compass-96ec812397e8. Retain cycles are often the main root cause for OOM or memory leaks.

**Comment by philipphofmann** [comment]
If we implement the heuristics approach described in [a blog post by Facebook](https://www.notion.so/sentry/Out-of-Memory-ec35713ded4f40e6bcd8ff7beeaff512#2596e6c1089f48e881563a63cde0f28b) we should consider restarting an app while being attached to the debugger. This could mess up the heuristics and could report false OOM.

**Comment by philipphofmann** [comment]
We can implement a heuristic-based approach for detecting OOM as described by [a blog post by Facebook](https://engineering.fb.com/2015/08/24/ios/reducing-fooms-in-the-facebook-ios-app/).
![image](https://user-images.githubusercontent.com/2443292/110913834-e71e3300-8315-11eb-87c9-2370fa46d87e.png)

This approach seems to have [false positives](https://stackoverflow.com/questions/48121843/suddenly-getting-many-fabric-out-of-memory-sessions-can-fabric-oom-reports-ever/48152858#48152858) when the app is in the background. Therefore we can only report OOM if the app was in the foreground.

**Comment by brustolin** [comment]
@philipphofmann  I guess you can use the low memory notification to add one more step in this process.

Was the low memory notification called last session? No -> OOM is not the problem. 

But I guess if the app tries to allocate a substantial chunk of memory the notification will not be fired.

**Comment by philipphofmann** [comment]
Good point @brustolin, but as far as I know there is no guarantee, that you receive the notification before an OOM like you mentioned.
