### ISSUE TITLE
Sentry crashes on `encodeObject`

### ISSUE THREAD

**Issue by borninla** [getsentry/sentry-cocoa#951]
### Environment

How do you use Sentry?

We use Sentry for error tracking and user feedback.

Which SDK and version?

Cocoa 6.1.4

### Steps to Reproduce

Not sure, the issue appears randomly. Here is the stack trace:

<img width="1199" alt="Screen Shot 2021-02-15 at 5 16 37 PM" src="https://user-images.githubusercontent.com/20800975/108007561-25dcf980-6fb3-11eb-8a19-33af8efda88d.png">

### Expected Result

We expected the crash reporter not to crash. :)

### Actual Result

The crash reporter crashed.

**Comment by philipphofmann** [comment]
Hi @borninla, 
Thanks for reaching out to us. This crash happens when synching the scope to SentryCrash in here https://github.com/getsentry/sentry-cocoa/blob/8a6182e4a0fc9ebf5e8ce541b545c9636e5bbaca/Sources/SentryCrash/Recording/Tools/SentryCrashJSONCodecObjC.m#L315

Can you give us a bit more context, please:
* Do you use the Scope manually, and if yes, how? 
* Can you please share a link to this issue?

**Comment by borninla** [comment]
> * Do you use the Scope manually, and if yes, how?

We call `SentrySDK.configureScope` to set an extra tag. This is done right after running `SentrySDK.start`.

> * Can you please share a link to this issue?

https://sentry.io/share/issue/a92a9da07e45459da1dbf2721fe16e01/

**Comment by philipphofmann** [comment]
Thanks for the info, @borninla. I'm currently not sure why this happens. We need to investigate this a bit further.

**Comment by borninla** [comment]
No worries, just thought I'd bring this up. I'll keep you guys posted if it happens again.

**Comment by philipphofmann** [comment]
As we didn't hear anything for a while, we are going to close this issue. Feel free to open it again.
